/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations';

export class ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseData {
    /**
    * Used to fetch the next page/set of results.
    */
    'nextPageToken'?: string;
    /**
    * List of RMA records.
    */
    'returnMerchandiseAuthorizations'?: Array<ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations>;
    /**
    * The total result set size, independent of pagination.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "returnMerchandiseAuthorizations",
            "baseName": "return_merchandise_authorizations",
            "type": "Array<ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseData.attributeTypeMap;
    }
}

