/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsShippingFee {
    /**
    * The amount of return shipping fee buyer paid.
    */
    'buyerPaidReturnShippingFeeAmount'?: string;
    /**
    * The amount of return shipping fee platform paid.
    */
    'platformPaidReturnShippingFeeAmount'?: string;
    /**
    * The amount of return shipping fee seller paid.
    */
    'sellerPaidReturnShippingFeeAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerPaidReturnShippingFeeAmount",
            "baseName": "buyer_paid_return_shipping_fee_amount",
            "type": "string"
        },
        {
            "name": "platformPaidReturnShippingFeeAmount",
            "baseName": "platform_paid_return_shipping_fee_amount",
            "type": "string"
        },
        {
            "name": "sellerPaidReturnShippingFeeAmount",
            "baseName": "seller_paid_return_shipping_fee_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202604SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsShippingFee.attributeTypeMap;
    }
}

