/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyFilters } from './SearchReturnMerchandiseAuthorizationRequestBodyFilters';
import { ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyPagination } from './SearchReturnMerchandiseAuthorizationRequestBodyPagination';
import { ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodySort } from './SearchReturnMerchandiseAuthorizationRequestBodySort';

export class ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBody {
    'filters'?: ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyFilters;
    'pagination'?: ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyPagination;
    'sort'?: ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodySort;
    /**
    * Whitelist of field names to return additional data in the response. Possible values: - `LINE_ITEMS` - `SKU_RETURN_REQUESTS`
    */
    'whitelistedDataFields'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyFilters"
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodyPagination"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBodySort"
        },
        {
            "name": "whitelistedDataFields",
            "baseName": "whitelisted_data_fields",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202604SearchReturnMerchandiseAuthorizationRequestBody.attributeTypeMap;
    }
}

