// Consolidated TypeScript model definitions for module: affiliate
// Merged from 35 source files.


// ==== SOURCE: V202309/AddShowcaseProductsoldRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309AddShowcaseProductsoldRequestBody {
    /**
    * The product IDs to add to the creator\'s showcase. The products can be added from my bound shop.
    */
    'productIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/AddShowcaseProductsoldResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309AddShowcaseProductsoldResponseData } from './AddShowcaseProductsoldResponseData';

export class Affiliate202309AddShowcaseProductsoldResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Affiliate202309AddShowcaseProductsoldResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Affiliate202309AddShowcaseProductsoldResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/AddShowcaseProductsoldResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309AddShowcaseProductsoldResponseDataErrors } from './AddShowcaseProductsoldResponseDataErrors';

export class Affiliate202309AddShowcaseProductsoldResponseData {
    /**
    * The errors when adding products to showcase
    */
    'errors'?: Array<Affiliate202309AddShowcaseProductsoldResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Affiliate202309AddShowcaseProductsoldResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/AddShowcaseProductsoldResponseDataErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail } from './AddShowcaseProductsoldResponseDataErrorsDetail';

export class Affiliate202309AddShowcaseProductsoldResponseDataErrors {
    /**
    * The error code when adding the product to showcase
    */
    'code'?: number;
    'detail'?: Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail;
    /**
    * The detailed error message when adding the product to showcase
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponseDataErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/AddShowcaseProductsoldResponseDataErrorsDetail.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail {
    /**
    * The failing product ID when the product is added to the creator\'s showcase
    */
    'productId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309AddShowcaseProductsoldResponseDataErrorsDetail.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetCreatorProfileoldResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetCreatorProfileoldResponseData } from './GetCreatorProfileoldResponseData';

export class Affiliate202309GetCreatorProfileoldResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Affiliate202309GetCreatorProfileoldResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Affiliate202309GetCreatorProfileoldResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetCreatorProfileoldResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetCreatorProfileoldResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetCreatorProfileoldResponseDataAvatar } from './GetCreatorProfileoldResponseDataAvatar';

export class Affiliate202309GetCreatorProfileoldResponseData {
    'avatar'?: Affiliate202309GetCreatorProfileoldResponseDataAvatar;
    /**
    * The creator\'s bound partner\'s ID
    */
    'partnerId'?: string;
    /**
    * The creator\'s bound partner\'s name
    */
    'partnerName'?: string;
    /**
    * The creator\'s granted permissions
    */
    'permissions'?: Array<string>;
    /**
    * The creator\'s register region
    */
    'registerRegion'?: string;
    /**
    * Represents the regions in which creators can promote products in their showcases, videos, and live streams.
    */
    'selectionRegion'?: string;
    /**
    * The creator\'s seller type if a creator has linked to a TikTok seller
    */
    'sellerType'?: string;
    /**
    * The creator\'s username in TikTok App Profile page, like creator_abc123
    */
    'userName'?: string;
    /**
    * The creator\'s user type
    */
    'userType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "Affiliate202309GetCreatorProfileoldResponseDataAvatar"
        },
        {
            "name": "partnerId",
            "baseName": "partner_id",
            "type": "string"
        },
        {
            "name": "partnerName",
            "baseName": "partner_name",
            "type": "string"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>"
        },
        {
            "name": "registerRegion",
            "baseName": "register_region",
            "type": "string"
        },
        {
            "name": "selectionRegion",
            "baseName": "selection_region",
            "type": "string"
        },
        {
            "name": "sellerType",
            "baseName": "seller_type",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "user_name",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "user_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetCreatorProfileoldResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetCreatorProfileoldResponseDataAvatar.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetCreatorProfileoldResponseDataAvatar {
    /**
    * The image height in pixels
    */
    'height'?: number;
    /**
    * The image\'s URL
    */
    'url'?: string;
    /**
    * The image width in pixels
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetCreatorProfileoldResponseDataAvatar.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetLiveRoomInfoResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetLiveRoomInfoResponseData } from './GetLiveRoomInfoResponseData';

export class Affiliate202309GetLiveRoomInfoResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Affiliate202309GetLiveRoomInfoResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Affiliate202309GetLiveRoomInfoResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetLiveRoomInfoResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetLiveRoomInfoResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetLiveRoomInfoResponseData {
    /**
    * The live room\'s ID
    */
    'id'?: string;
    /**
    * The start time of broadcasting
    */
    'startTime'?: number;
    /**
    * The live room\'s status
    */
    'status'?: string;
    /**
    * The live room\'s title
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetLiveRoomInfoResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShopProductslegacyResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShopProductslegacyResponseData } from './GetShopProductslegacyResponseData';

export class Affiliate202309GetShopProductslegacyResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Affiliate202309GetShopProductslegacyResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Affiliate202309GetShopProductslegacyResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductslegacyResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShopProductslegacyResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShopProductslegacyResponseDataProducts } from './GetShopProductslegacyResponseDataProducts';

export class Affiliate202309GetShopProductslegacyResponseData {
    /**
    * The pagination token is a cursor used for pagination. The token is returned in the previous pagination query to determine the current position. It will be empty when there aren\'t any products to search for.
    */
    'nextPageToken'?: string;
    /**
    * The searched product list. It will be empty when there are no search results.
    */
    'products'?: Array<Affiliate202309GetShopProductslegacyResponseDataProducts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Affiliate202309GetShopProductslegacyResponseDataProducts>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductslegacyResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShopProductslegacyResponseDataProducts.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShopProductslegacyResponseDataProductsImages } from './GetShopProductslegacyResponseDataProductsImages';
import { Affiliate202309GetShopProductslegacyResponseDataProductsPrice } from './GetShopProductslegacyResponseDataProductsPrice';

export class Affiliate202309GetShopProductslegacyResponseDataProducts {
    /**
    * Showcase add status with possible values: - ADDABLE - ADDED - REJECTED
    */
    'addedStatus'?: string;
    /**
    * The brand name a seller has set for a product.
    */
    'brandName'?: string;
    /**
    * TikTok product ID.
    */
    'id'?: string;
    /**
    * Images of a product.
    */
    'images'?: Array<Affiliate202309GetShopProductslegacyResponseDataProductsImages>;
    'price'?: Affiliate202309GetShopProductslegacyResponseDataProductsPrice;
    /**
    * The number of products that have been sold.
    */
    'salesCount'?: number;
    /**
    * Product name.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addedStatus",
            "baseName": "added_status",
            "type": "string"
        },
        {
            "name": "brandName",
            "baseName": "brand_name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Affiliate202309GetShopProductslegacyResponseDataProductsImages>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Affiliate202309GetShopProductslegacyResponseDataProductsPrice"
        },
        {
            "name": "salesCount",
            "baseName": "sales_count",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductslegacyResponseDataProducts.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShopProductslegacyResponseDataProductsImages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShopProductslegacyResponseDataProductsImages {
    /**
    * The height of the product image.
    */
    'height'?: number;
    /**
    * The URL of the product image.
    */
    'url'?: string;
    /**
    * The width of the product image.
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductslegacyResponseDataProductsImages.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShopProductslegacyResponseDataProductsPrice.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShopProductslegacyResponseDataProductsPrice {
    /**
    * Product price with two decimal places.
    */
    'amount'?: string;
    /**
    * Product price currency, based on region where creators can sell.
    */
    'currency'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductslegacyResponseDataProductsPrice.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShowcaseProductsoldResponseData } from './GetShowcaseProductsoldResponseData';

export class Affiliate202309GetShowcaseProductsoldResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Affiliate202309GetShowcaseProductsoldResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Affiliate202309GetShowcaseProductsoldResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShowcaseProductsoldResponseDataProducts } from './GetShowcaseProductsoldResponseDataProducts';

export class Affiliate202309GetShowcaseProductsoldResponseData {
    /**
    * The product IDs in the livebag among the products returned in this response.
    */
    'liveProductIds'?: Array<string>;
    /**
    * Returns the token to get the next page of products if the response does not return all the products, otherwise returns an empty string.
    */
    'nextPageToken'?: string;
    /**
    * The product\'s detailed info fields
    */
    'products'?: Array<Affiliate202309GetShowcaseProductsoldResponseDataProducts>;
    /**
    * Returns the total number of products in the showcase.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "liveProductIds",
            "baseName": "live_product_ids",
            "type": "Array<string>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Affiliate202309GetShowcaseProductsoldResponseDataProducts>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProducts.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsAddition } from './GetShowcaseProductsoldResponseDataProductsAddition';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsCommission } from './GetShowcaseProductsoldResponseDataProductsCommission';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages } from './GetShowcaseProductsoldResponseDataProductsMainImages';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsPrice } from './GetShowcaseProductsoldResponseDataProductsPrice';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsStatus } from './GetShowcaseProductsoldResponseDataProductsStatus';

export class Affiliate202309GetShowcaseProductsoldResponseDataProducts {
    'addition'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsAddition;
    'commission'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsCommission;
    /**
    * The product detail page URL of a Tiktok product
    */
    'detailUrl'?: string;
    /**
    * The product\'s product ID
    */
    'id'?: string;
    /**
    * The main images of the products
    */
    'mainImages'?: Array<Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages>;
    /**
    * The original product URL if the product is a third-party product
    */
    'originalUrl'?: string;
    'price'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsPrice;
    /**
    * The regions where the product can be sold
    */
    'saleRegions'?: Array<string>;
    /**
    * The shop name of the seller
    */
    'shopName'?: string;
    /**
    * The source of the product. Field values: THIRD_PARTY: the product is from third-party seller AFFILIATE: the product is from TikTok affiliate seller TIKTOK_STORE: the product is from seller\'s own store
    */
    'source'?: string;
    'status'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsStatus;
    /**
    * The product\'s title
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addition",
            "baseName": "addition",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsAddition"
        },
        {
            "name": "commission",
            "baseName": "commission",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsCommission"
        },
        {
            "name": "detailUrl",
            "baseName": "detail_url",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "mainImages",
            "baseName": "main_images",
            "type": "Array<Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages>"
        },
        {
            "name": "originalUrl",
            "baseName": "original_url",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsPrice"
        },
        {
            "name": "saleRegions",
            "baseName": "sale_regions",
            "type": "Array<string>"
        },
        {
            "name": "shopName",
            "baseName": "shop_name",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsStatus"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProducts.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsAddition.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage } from './GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsAddition {
    /**
    * The product\'s customized main image
    */
    'customizedMainImage'?: Array<Affiliate202309GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customizedMainImage",
            "baseName": "customized_main_image",
            "type": "Array<Affiliate202309GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsAddition.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage {
    /**
    * The image height in pixels
    */
    'height'?: number;
    /**
    * The image\'s URL
    */
    'url'?: string;
    /**
    * The image width in pixels
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsAdditionCustomizedMainImage.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsCommission.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsCommission {
    /**
    * The commission rate for this product is set by merchants for creators\' public promotion. - The range of this value is [100, 8000].  - This value equals actual commission rate multi 10000. For example: 3000 means the actual commission rate is 30.00%, and 3555 means 35.55%
    */
    'commissionRate'?: number;
    /**
    * The reward commission rate that has already been included in the total commission rate. - This value equals actual commission rate multi 10000. For example: 3000 means the actual commission rate is 30.00%, and 3555 means 35.55%
    */
    'inclusiveRewardCommissionRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commissionRate",
            "baseName": "commission_rate",
            "type": "number"
        },
        {
            "name": "inclusiveRewardCommissionRate",
            "baseName": "inclusive_reward_commission_rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsCommission.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsMainImages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages {
    /**
    * The image height in pixels
    */
    'height'?: number;
    /**
    * The image\'s URL
    */
    'url'?: string;
    /**
    * The image width in pixels
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsMainImages.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsPrice.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice } from './GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice } from './GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice';
import { Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice } from './GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsPrice {
    'originalPrice'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice;
    'platformDiscountPrice'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice;
    'sellerDiscountPrice'?: Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "originalPrice",
            "baseName": "original_price",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice"
        },
        {
            "name": "platformDiscountPrice",
            "baseName": "platform_discount_price",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice"
        },
        {
            "name": "sellerDiscountPrice",
            "baseName": "seller_discount_price",
            "type": "Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsPrice.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice {
    /**
    * The price currency
    */
    'currency'?: string;
    /**
    * The original highest SPU price of the product
    */
    'highestAmount'?: string;
    /**
    * The original lowest SPU price of the product
    */
    'lowestAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "highestAmount",
            "baseName": "highest_amount",
            "type": "string"
        },
        {
            "name": "lowestAmount",
            "baseName": "lowest_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceOriginalPrice.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice {
    /**
    * The price currency
    */
    'currency'?: string;
    /**
    * The highest SPU price with platform discount of the product
    */
    'highestAmount'?: string;
    /**
    * The lowest SPU price with platform discount of the product
    */
    'lowestAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "highestAmount",
            "baseName": "highest_amount",
            "type": "string"
        },
        {
            "name": "lowestAmount",
            "baseName": "lowest_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsPricePlatformDiscountPrice.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice {
    /**
    * The price currency
    */
    'currency'?: string;
    /**
    * The highest SPU price with seller discount of the product
    */
    'highestAmount'?: string;
    /**
    * The lowest SPU price with seller discount of the product
    */
    'lowestAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "highestAmount",
            "baseName": "highest_amount",
            "type": "string"
        },
        {
            "name": "lowestAmount",
            "baseName": "lowest_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsPriceSellerDiscountPrice.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShowcaseProductsoldResponseDataProductsStatus.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309GetShowcaseProductsoldResponseDataProductsStatus {
    /**
    * The product\'s added status in the showcase/livebag according to the provided origin in the request  Field values: NOT_ADDED: The product has not been added to showcase, or to the live stream if the origin field in the request is LIVE. ADDED: The product has been added to the showcase, or to the live room if the origin field in the request is LIVE. REJECTED: The product is rejected and can not be added.
    */
    'addedStatus'?: string;
    /**
    * The inventory status of the product Field values: IN_STOCK: The product is in stock SOLD_OUT: The product has been sold out
    */
    'inventoryStatus'?: string;
    /**
    * Whether the product has been hidden by the creator
    */
    'isHidden'?: boolean;
    /**
    * The review status represents whether the merchant approves the creator of promoting this product.  Field values: APPROVED: The product is approved UNDER_REVIEW: The product is still under review CHANGES_UNDER_REVIEW: The updates to this product are still under review. UNAVAILABLE: The product is unavailable. REJECTED: The product is rejected. ZERO_COMMISSION: the product will not contribute to any commission.
    */
    'reviewStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addedStatus",
            "baseName": "added_status",
            "type": "string"
        },
        {
            "name": "inventoryStatus",
            "baseName": "inventory_status",
            "type": "string"
        },
        {
            "name": "isHidden",
            "baseName": "is_hidden",
            "type": "boolean"
        },
        {
            "name": "reviewStatus",
            "baseName": "review_status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShowcaseProductsoldResponseDataProductsStatus.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/RemoveShowcaseProductsoldRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309RemoveShowcaseProductsoldRequestBody {
    /**
    * The product IDs to delete from the creator\'s showcase. The maximum number of products to delete at once is 200.
    */
    'productIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309RemoveShowcaseProductsoldRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/RemoveShowcaseProductsoldResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309RemoveShowcaseProductsoldResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309RemoveShowcaseProductsoldResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/TopShowcaseProductsoldRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309TopShowcaseProductsoldRequestBody {
    /**
    * The product IDs to move to the top in a creator\'s showcase. If multiple products are provided, they will display according to the order passed in this parameter.
    */
    'productIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309TopShowcaseProductsoldRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/TopShowcaseProductsoldResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202309TopShowcaseProductsoldResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309TopShowcaseProductsoldResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202402/CheckAnchorPrerequisitesRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202402CheckAnchorPrerequisitesRequestBody {
    /**
    * Product id that wanted to been checked.
    */
    'productId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202402CheckAnchorPrerequisitesRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202402/CheckAnchorPrerequisitesResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202402CheckAnchorPrerequisitesResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202402CheckAnchorPrerequisitesResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202403/CheckAnchorContentRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202403CheckAnchorContentRequestBody {
    /**
    * Anchor title that you want show in anchor.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202403CheckAnchorContentRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202403/CheckAnchorContentResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Affiliate202403CheckAnchorContentResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202403CheckAnchorContentResponse.attributeTypeMap;
    }
}


