// Consolidated TypeScript model definitions for module: authorization
// Merged from 14 source files.


// ==== SOURCE: V202309/GetAuthorizedShopsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202309GetAuthorizedShopsResponseData } from './GetAuthorizedShopsResponseData';

export class Authorization202309GetAuthorizedShopsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Authorization202309GetAuthorizedShopsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Authorization202309GetAuthorizedShopsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202309GetAuthorizedShopsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetAuthorizedShopsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202309GetAuthorizedShopsResponseDataShops } from './GetAuthorizedShopsResponseDataShops';

export class Authorization202309GetAuthorizedShopsResponseData {
    /**
    * The list of shops that a seller has authorized for the app.
    */
    'shops'?: Array<Authorization202309GetAuthorizedShopsResponseDataShops>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shops",
            "baseName": "shops",
            "type": "Array<Authorization202309GetAuthorizedShopsResponseDataShops>"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202309GetAuthorizedShopsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetAuthorizedShopsResponseDataShops.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Authorization202309GetAuthorizedShopsResponseDataShops {
    /**
    * An encrypted token used to securely identify a shop in API requests. There is no need for decryption on the receiving end.
    */
    'cipher'?: string;
    /**
    * The TikTok Shop code, which is also displayed on Seller Center.
    */
    'code'?: string;
    /**
    * An internal identifier for the TikTok Shop.
    */
    'id'?: string;
    /**
    * The TikTok Shop name.
    */
    'name'?: string;
    /**
    * The region of the shop.
    */
    'region'?: string;
    /**
    * The type of seller. Possible values: - CROSS_BORDER: Cross border sellers with multiple shops in different countries. - LOCAL: Local sellers with only 1 shop.
    */
    'sellerType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cipher",
            "baseName": "cipher",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "sellerType",
            "baseName": "seller_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202309GetAuthorizedShopsResponseDataShops.attributeTypeMap;
    }
}



// ==== SOURCE: V202312/GetWidgetTokenResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202312GetWidgetTokenResponseData } from './GetWidgetTokenResponseData';

export class Authorization202312GetWidgetTokenResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Authorization202312GetWidgetTokenResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Authorization202312GetWidgetTokenResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202312GetWidgetTokenResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202312/GetWidgetTokenResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202312GetWidgetTokenResponseDataWidgetToken } from './GetWidgetTokenResponseDataWidgetToken';

export class Authorization202312GetWidgetTokenResponseData {
    'widgetToken'?: Authorization202312GetWidgetTokenResponseDataWidgetToken;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "widgetToken",
            "baseName": "widget_token",
            "type": "Authorization202312GetWidgetTokenResponseDataWidgetToken"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202312GetWidgetTokenResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202312/GetWidgetTokenResponseDataWidgetToken.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Authorization202312GetWidgetTokenResponseDataWidgetToken {
    /**
    * widget token expire timestamp, usually 5 minutes
    */
    'expireAt'?: number;
    /**
    * token used to pass widget api
    */
    'token'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expireAt",
            "baseName": "expire_at",
            "type": "number"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202312GetWidgetTokenResponseDataWidgetToken.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/GetWidgetTokenResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202401GetWidgetTokenResponseData } from './GetWidgetTokenResponseData';

export class Authorization202401GetWidgetTokenResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Authorization202401GetWidgetTokenResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Authorization202401GetWidgetTokenResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202401GetWidgetTokenResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/GetWidgetTokenResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202401GetWidgetTokenResponseDataWidgetToken } from './GetWidgetTokenResponseDataWidgetToken';

export class Authorization202401GetWidgetTokenResponseData {
    'widgetToken'?: Authorization202401GetWidgetTokenResponseDataWidgetToken;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "widgetToken",
            "baseName": "widget_token",
            "type": "Authorization202401GetWidgetTokenResponseDataWidgetToken"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202401GetWidgetTokenResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/GetWidgetTokenResponseDataWidgetToken.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Authorization202401GetWidgetTokenResponseDataWidgetToken {
    /**
    * widget token expire timestamp, usually 5 minutes
    */
    'expireAt'?: number;
    /**
    * token used to pass widget api
    */
    'token'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expireAt",
            "baseName": "expire_at",
            "type": "number"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202401GetWidgetTokenResponseDataWidgetToken.attributeTypeMap;
    }
}



// ==== SOURCE: V202405/GetAuthorizedCategoryAssetsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202405GetAuthorizedCategoryAssetsResponseData } from './GetAuthorizedCategoryAssetsResponseData';

export class Authorization202405GetAuthorizedCategoryAssetsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Authorization202405GetAuthorizedCategoryAssetsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Authorization202405GetAuthorizedCategoryAssetsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202405GetAuthorizedCategoryAssetsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202405/GetAuthorizedCategoryAssetsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets } from './GetAuthorizedCategoryAssetsResponseDataCategoryAssets';

export class Authorization202405GetAuthorizedCategoryAssetsResponseData {
    /**
    * The list of business category assets that a partner has authorized for the app.
    */
    'categoryAssets'?: Array<Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryAssets",
            "baseName": "category_assets",
            "type": "Array<Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets>"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202405GetAuthorizedCategoryAssetsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202405/GetAuthorizedCategoryAssetsResponseDataCategoryAssets.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory } from './GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory';

export class Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets {
    'category'?: Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory;
    /**
    * An encrypted token used to securely identify a partner in API requests. There is no need for decryption on the receiving end.
    */
    'cipher'?: string;
    /**
    * The target market of the business category.
    */
    'targetMarket'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory"
        },
        {
            "name": "cipher",
            "baseName": "cipher",
            "type": "string"
        },
        {
            "name": "targetMarket",
            "baseName": "target_market",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets.attributeTypeMap;
    }
}



// ==== SOURCE: V202405/GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory {
    /**
    * The ID of the business category. Use this field to verify if the partner has authorized the correct category. Otherwise, request re-authorization from the partner by referring to the [Partner authorization guide](https://partner.tiktokshop.com/docv2/page/669a301bd92cd602fd403ff9).
    */
    'id'?: number;
    /**
    * The name of the business category. This name may change.
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory.attributeTypeMap;
    }
}



// ==== SOURCE: V202403/DeauthorizeShopResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Authorization202403DeauthorizeShopResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202403DeauthorizeShopResponse.attributeTypeMap;
    }
}


