// Consolidated TypeScript model definitions for module: customerService
// Merged from 34 source files.


// ==== SOURCE: V202407/GetCustomerServicePerformanceResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202407GetCustomerServicePerformanceResponseData } from './GetCustomerServicePerformanceResponseData';

export class CustomerService202407GetCustomerServicePerformanceResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202407GetCustomerServicePerformanceResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202407GetCustomerServicePerformanceResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202407GetCustomerServicePerformanceResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202407/GetCustomerServicePerformanceResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202407GetCustomerServicePerformanceResponseDataPerformance } from './GetCustomerServicePerformanceResponseDataPerformance';

export class CustomerService202407GetCustomerServicePerformanceResponseData {
    'performance'?: CustomerService202407GetCustomerServicePerformanceResponseDataPerformance;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "performance",
            "baseName": "performance",
            "type": "CustomerService202407GetCustomerServicePerformanceResponseDataPerformance"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202407GetCustomerServicePerformanceResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202407/GetCustomerServicePerformanceResponseDataPerformance.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202407GetCustomerServicePerformanceResponseDataPerformance {
    /**
    * The percentage of successfully converted customers based on the total number of potential customers.
    */
    'conversionRate'?: string;
    /**
    * The revenue generated from orders placed by customers within 7 days of your response to their chat.
    */
    'csGuidedGmv'?: string;
    /**
    * Currency Type. Three-letter code, see [Currency Codes](https://www.iso.org/iso-4217-currency-codes.html).
    */
    'currency'?: string;
    /**
    * The percentage of chat support sessions of which the first response happens within 24 hours. The sessions which started in the specified time slot are included in calculation. - Automated responses such as FAQ cards are regarded as responses within 24 hours. - Sessions initiated during vacation mode are excluded from this calculation.
    */
    'responsePercentage'?: string;
    /**
    * The average first response time in minutes for chat support sessions. The sessions which started in the specified time slot are included in calculation.
    */
    'responseTimeMins'?: string;
    /**
    * The percentage of chat support sessions rated \'Satisfied\' (4 or 5 stars). The sessions of which the rating occurred in the specified time slot are included in the calculation; the sessions without rate are not included in the calculation.
    */
    'satisfactionPercentage'?: string;
    /**
    * The total number of chat support sessions initiated by customers. A session starts when a customer first clicks an FAQ card or sends a message (text, image, video, emoji, product card, order card, etc.) in chat. The sessions which started in the specified time slot are included in calculation.
    */
    'supportSessionCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversionRate",
            "baseName": "conversion_rate",
            "type": "string"
        },
        {
            "name": "csGuidedGmv",
            "baseName": "cs_guided_gmv",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "responsePercentage",
            "baseName": "response_percentage",
            "type": "string"
        },
        {
            "name": "responseTimeMins",
            "baseName": "response_time_mins",
            "type": "string"
        },
        {
            "name": "satisfactionPercentage",
            "baseName": "satisfaction_percentage",
            "type": "string"
        },
        {
            "name": "supportSessionCount",
            "baseName": "support_session_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/CreateConversationRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309CreateConversationRequestBody {
    /**
    * Buyer\'s user ID The value is the same as `data.orders.user_id` in the response data of [Get Order Detail](650aa8ccc16ffe02b8f167a0).
    */
    'buyerUserId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerUserId",
            "baseName": "buyer_user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309CreateConversationRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/CreateConversationResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309CreateConversationResponseData } from './CreateConversationResponseData';

export class CustomerService202309CreateConversationResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309CreateConversationResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309CreateConversationResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309CreateConversationResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/CreateConversationResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309CreateConversationResponseData {
    /**
    * Converstaion ID. The unique identifier for a conversation between the buyer and a shop.
    */
    'conversationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309CreateConversationResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetAgentSettingsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetAgentSettingsResponseData } from './GetAgentSettingsResponseData';

export class CustomerService202309GetAgentSettingsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309GetAgentSettingsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309GetAgentSettingsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetAgentSettingsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetAgentSettingsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309GetAgentSettingsResponseData {
    /**
    * Whether the current agent can accept chat. If true, the agent will receive auto-assigned chats. The agent can manually select chats to respond.  If false, the agent will receive manually assigned chats only. 
    */
    'canAcceptChat'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canAcceptChat",
            "baseName": "can_accept_chat",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetAgentSettingsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationMessagesResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationMessagesResponseData } from './GetConversationMessagesResponseData';

export class CustomerService202309GetConversationMessagesResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309GetConversationMessagesResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309GetConversationMessagesResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationMessagesResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationMessagesResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationMessagesResponseDataMessages } from './GetConversationMessagesResponseDataMessages';

export class CustomerService202309GetConversationMessagesResponseData {
    /**
    * Messages in conversation.
    */
    'messages'?: Array<CustomerService202309GetConversationMessagesResponseDataMessages>;
    /**
    * The index indicates where we should start on the next page.  If there is no more record, this field will be \"\"(empty string). Put this value to request param \"page_token\" for the next page query.
    */
    'nextPageToken'?: string;
    /**
    * If your app encounters a message type it doesn\'t support, you can display the text to guide the user to check the message in TikTok Shop. The content of the message depends on the specific `locale`.
    */
    'unsupportedMsgTips'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<CustomerService202309GetConversationMessagesResponseDataMessages>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "unsupportedMsgTips",
            "baseName": "unsupported_msg_tips",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationMessagesResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationMessagesResponseDataMessages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationMessagesResponseDataMessagesSender } from './GetConversationMessagesResponseDataMessagesSender';

export class CustomerService202309GetConversationMessagesResponseDataMessages {
    /**
    * Message content, in JSON serialized string. Examples of content for each type of message are listed below: - TEXT:  ``` {     \"content\": \"simple text\" } ```  - IMAGE:  ``` {     \"height\": \"290\",     \"url\": \"https://tosv.boei18n.byted.org/obj/temai-im/FszkJ53nSapYG6KDaJQmqR3jjoZGwww304-290\",     \"width\": \"304\" } ```  - PRODUCT_CARD, BUYER_ENTER_FROM_PRODUCT: ``` {     \"product_id\": \"12345\" } ```  - ORDER_CARD, BUYER_ENTER_FROM_ORDER : ``` {     \"order_id\": \"12345\" } ``` - LOGISTICS_CARD: ``` {     \"order_id\": \"12345\",     \"package_id\": \"321\" } ```  - RETURN_REFUND_CARD: ``` {     \"order_id\": \"12345\",     \"sku_id\": \"45678\" } ```  - VIDEO: ``` {     \"url\": \"https://video-boei18n.byted.org/storage/v1/tos-boei18n-v-c72c01/e8240f35244646428df9c3244d1a7408?x-tos-algorithm=v2&x-tos-authkey=5bf25627da095a5cba28ace592de46cc&x-tos-expires=1681980481&x-tos-signature=r_bRxtrvGhXAuZgMmNhlZ_Upqzg\",     \"cover\": \"https://p-boei18n.byted.org/tos-boei18n-v-c72c01/o8keEOhzTcNCcJyAbkWZwpLIyTfkJxcGbRBvLP~tplv-jvtte31kaf-origin-jpeg.jpeg?\",     \"width\": 640,     \"height\": 360,     \"duration\": \"20.504\",     \"vid\": \"v0e30cg700f7cgcmu8jc77u9e2bdp95g\",     \"expire_time\": \"1681980481\",     \"format\": \"mp4\",     \"size\": 400000,     \"bit_rate\": 156067,     \"quality\": \"original\",     \"codec_type\": \"h264\" } ```  - ALLOCATED_SERVICE, NOTIFICATION, BUYER_ENTER_FROM_TRANSFER, OTHER:  ``` {     \"content\": \"simple text\" } ```  - COUPON_CARD: ``` {     \"coupon_id\": \"7262992004278206762\" } ``` Note: Use [Get Coupon](6699dce0de15e502ed219e37) for the details of the coupon.
    */
    'content'?: string;
    /**
    * Unix timestamp for creating the message in seconds.
    */
    'createTime'?: number;
    /**
    * {   \"packages\": [     {       \"package_id\": \"456\",       \"product_name\": \"Nutrition\",       \"product_image\": \"https://cdn-us.com/us/123jpeg:1000:1000.jpeg?dr=123&t=555\",       \"paid_price\": \"$0.01\",       \"quantity\": 1,       \"predict_delivery_time_min\": 1763198750000,       \"predict_delivery_time_max\": 1763457950000,       \"delivery_option\": \"Standard shipping\",       \"tracking_number\": \"1Z789\",       \"shipping_provider_name\": \"UPS\",       \"tracking\": [         {           \"description\": \"Package has been delivered!\",           \"update_time_millis\": 1763954669267         },         {           \"description\": \"Arrived at the carrier\'s facility.\",           \"update_time_millis\": 1763954598311         },         {           \"description\": \"Package picked up.\",           \"update_time_millis\": 1763954598024         },         {           \"description\": \"Order packed and ready for dropoff at carrier\'s facility.\",           \"update_time_millis\": 1763451813897         },         {           \"description\": \"Order placed.\",           \"update_time_millis\": 1763112346906         }       ]     }   ] }
    */
    'data'?: string;
    /**
    * Message ID.
    */
    'id'?: string;
    /**
    * Message index. This field can be used to sort messages. \"index\" means the order of the message in the conversation. This value is unique for every message in a conversation. This value is time-related, meaning a newer message will get a larger \"index\". But it is not strictly increasing.
    */
    'index'?: string;
    /**
    * Whether this message should be displayed to customer service. For example, the buyer will receive a rating request message at the end of the conversation from the system. You should not present this type of message to the seller or the customer support agents.
    */
    'isVisible'?: boolean;
    /**
    * - PRODUCT_CARD Product card shared: - Product ID: 1732529206731441911;  - Product name: Áo Khoác Cardigan Logo Thêu Phong Cách Hàn Quốc By Zonef, Áo Khoác Thu Đông Chất Vải Cotton Tổ Ong Nam Nữ Unisex;  - Product price: ;  - Strike-through price:  - Sold: 40013.   View full details at: https://seller-vn.tiktok.com/product/manage?search_content=1732529206731441911
    */
    'plaintext'?: string;
    'sender'?: CustomerService202309GetConversationMessagesResponseDataMessagesSender;
    /**
    * Message type. Possible enumerations: - TEXT - IMAGE - ALLOCATED_SERVICE - A customer service agent joins the conversation. - NOTIFICATION - Notification from the system. - BUYER_ENTER_FROM_TRANSFER : The conversation is transferred to another customer service agent. - BUYER_ENTER_FROM_PRODUCT : The buyer is viewing a product before sending this message. - BUYER_ENTER_FROM_ORDER : The buyer is viewing an order before sending this message. - PRODUCT_CARD - EMOTICONS - ORDER_CARD - VIDEO - RETURN_REFUND_CARD: Return/refund card. - COUPON_CARD - LOGISTICS_CARD - OTHER: Messages of types not supported in this API.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "string"
        },
        {
            "name": "isVisible",
            "baseName": "is_visible",
            "type": "boolean"
        },
        {
            "name": "plaintext",
            "baseName": "plaintext",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "CustomerService202309GetConversationMessagesResponseDataMessagesSender"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationMessagesResponseDataMessages.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationMessagesResponseDataMessagesSender.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309GetConversationMessagesResponseDataMessagesSender {
    /**
    * Sender\'s avatar URL. 
    */
    'avatar'?: string;
    /**
    * Sender\'s ID. These are IM IDs, and can not be used to query orders.
    */
    'imUserId'?: string;
    /**
    * Sender\'s nickname. - For shops, the nickname is the shop\'s name.  - For customer service, the nickname is the customer service\'s name.  - For buyers, the nickname is the buyer\'s nickname on TikTok.  You can set the nicknames for shops and customer service agents on Seller Center.  
    */
    'nickname'?: string;
    /**
    * Sender\'s role. Possible enumerations: - `BUYER` - `SHOP` - `CUSTOMER_SERVICE` - `SYSTEM` - `ROBOT` For `SYSTEM` and `ROBOT` role, the value of `im_user_id`, `nickname`, and `avatar` are the same as those of the `SHOP` role.
    */
    'role'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "imUserId",
            "baseName": "im_user_id",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationMessagesResponseDataMessagesSender.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationsResponseData } from './GetConversationsResponseData';

export class CustomerService202309GetConversationsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309GetConversationsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309GetConversationsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationsResponseDataConversations } from './GetConversationsResponseDataConversations';

export class CustomerService202309GetConversationsResponseData {
    /**
    * Conversation info. 
    */
    'conversations'?: Array<CustomerService202309GetConversationsResponseDataConversations>;
    /**
    * The index indicates where we should start on the next page. If there is no more record, this field will be \"\"(empty string). Put this value to request param \"page_token\" for the next page query.
    */
    'nextPageToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversations",
            "baseName": "conversations",
            "type": "Array<CustomerService202309GetConversationsResponseDataConversations>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponseDataConversations.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationsResponseDataConversationsLatestMessage } from './GetConversationsResponseDataConversationsLatestMessage';
import { CustomerService202309GetConversationsResponseDataConversationsParticipants } from './GetConversationsResponseDataConversationsParticipants';

export class CustomerService202309GetConversationsResponseDataConversations {
    /**
    * Whether customer service agent can send message in this conversation. Under any of the following circumstances, the CS agent can send messages: 1. There has been a prior conversation between the buyer and the shop within the last 30 days. 2. The buyer placed an order at the shop within the past 60 days. 3. The buyer has a history of returns or refunds at the shop.
    */
    'canSendMessage'?: boolean;
    /**
    * Unix timestamp when the conversation was created. In seconds.
    */
    'createTime'?: number;
    /**
    * Current session id.
    */
    'curSessionId'?: string;
    /**
    * Conversation ID
    */
    'id'?: string;
    'latestMessage'?: CustomerService202309GetConversationsResponseDataConversationsLatestMessage;
    /**
    * Number of participants in the conversation. - If there has been no customer service agent in the conversation, the value is `2`: the shop and the buyer; - Otherwise, the value is `3`: the shop, the buyer, and the customer service agent.
    */
    'participantCount'?: number;
    /**
    * Conversation participants.
    */
    'participants'?: Array<CustomerService202309GetConversationsResponseDataConversationsParticipants>;
    /**
    * Number of messages unread by the customer service agent.
    */
    'unreadCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canSendMessage",
            "baseName": "can_send_message",
            "type": "boolean"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "curSessionId",
            "baseName": "cur_session_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "latestMessage",
            "baseName": "latest_message",
            "type": "CustomerService202309GetConversationsResponseDataConversationsLatestMessage"
        },
        {
            "name": "participantCount",
            "baseName": "participant_count",
            "type": "number"
        },
        {
            "name": "participants",
            "baseName": "participants",
            "type": "Array<CustomerService202309GetConversationsResponseDataConversationsParticipants>"
        },
        {
            "name": "unreadCount",
            "baseName": "unread_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponseDataConversations.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponseDataConversationsLatestMessage.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309GetConversationsResponseDataConversationsLatestMessageSender } from './GetConversationsResponseDataConversationsLatestMessageSender';

export class CustomerService202309GetConversationsResponseDataConversationsLatestMessage {
    /**
    * Message content, in JSON serialized string. Examples of content for each type of message are listed below: - TEXT:  ``` {     \"content\": \"simple text\" } ```  - IMAGE:  ``` {     \"height\": \"290\",     \"url\": \"https://tosv.boei18n.byted.org/obj/temai-im/FszkJ53nSapYG6KDaJQmqR3jjoZGwww304-290\",     \"width\": \"304\" } ```  - PRODUCT_CARD, BUYER_ENTER_FROM_PRODUCT: ``` {     \"product_id\": \"12345\" } ```  - ORDER_CARD, BUYER_ENTER_FROM_ORDER : ``` {     \"order_id\": \"12345\" } ```  - RETURN_REFUND_CARD: ``` {     \"order_id\": \"12345\",     \"sku_id\": \"45678\" } ```  - VIDEO: ``` {     \"url\": \"https://video-boei18n.byted.org/storage/v1/tos-boei18n-v-c72c01/e8240f35244646428df9c3244d1a7408?x-tos-algorithm=v2&x-tos-authkey=5bf25627da095a5cba28ace592de46cc&x-tos-expires=1681980481&x-tos-signature=r_bRxtrvGhXAuZgMmNhlZ_Upqzg\",     \"cover\": \"https://p-boei18n.byted.org/tos-boei18n-v-c72c01/o8keEOhzTcNCcJyAbkWZwpLIyTfkJxcGbRBvLP~tplv-jvtte31kaf-origin-jpeg.jpeg?\",     \"width\": 640,     \"height\": 360,     \"duration\": \"20.504\",     \"vid\": \"v0e30cg700f7cgcmu8jc77u9e2bdp95g\",     \"expire_time\": \"1681980481\",     \"format\": \"mp4\",     \"size\": 400000,     \"bit_rate\": 156067,     \"quality\": \"original\",     \"codec_type\": \"h264\" } ```  - ALLOCATED_SERVICE, NOTIFICATION, BUYER_ENTER_FROM_TRANSFER, OTHER:  ``` {     \"content\": \"simple text\" } ```  - COUPON_CARD: ``` {     \"coupon_id\": \"7262992004278206762\" } ``` Note: Use [Get Coupon](6699dce0de15e502ed219e37) for the details of the coupon.
    */
    'content'?: string;
    /**
    * Unix timestamp for creating the message in seconds.
    */
    'createTime'?: number;
    /**
    * Message ID.
    */
    'id'?: string;
    /**
    * Message index. This field can be used to sort messages. \"index\" means the order of the message in the conversation. This value is unique for every message in a conversation. This value is time-related, meaning a newer message will get a larger \"index\". But it is not strictly increasing.
    */
    'index'?: string;
    /**
    * Whether this message should be displayed to customer service. For example, the buyer will receive a rating request message at the end of the conversation from the system. You should not present this type of message to the seller or the customer support agents.
    */
    'isVisible'?: boolean;
    'sender'?: CustomerService202309GetConversationsResponseDataConversationsLatestMessageSender;
    /**
    * Message type. Possible enumerations: - TEXT - IMAGE - ALLOCATED_SERVICE - A customer service agent joins the conversation. - NOTIFICATION - Notification from the system. - BUYER_ENTER_FROM_TRANSFER : The conversation is transferred to another customer service agent. - BUYER_ENTER_FROM_PRODUCT : The buyer is viewing a product before sending this message. - BUYER_ENTER_FROM_ORDER : The buyer is viewing an order before sending this message. - PRODUCT_CARD - EMOTICONS - ORDER_CARD - VIDEO - RETURN_REFUND_CARD: Return/refund card. - COUPON_CARD - OTHER: Messages of types not supported in this API.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "string"
        },
        {
            "name": "isVisible",
            "baseName": "is_visible",
            "type": "boolean"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "CustomerService202309GetConversationsResponseDataConversationsLatestMessageSender"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponseDataConversationsLatestMessage.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponseDataConversationsLatestMessageSender.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309GetConversationsResponseDataConversationsLatestMessageSender {
    /**
    * Sender\'s avatar URL. 
    */
    'avatar'?: string;
    /**
    * Sender\'s IM ID. Sender\'s unique identifier in TikTok Shop\'s IM system. 
    */
    'imUserId'?: string;
    /**
    * Sender\'s nickname. - For shops, the nickname is the shop\'s name.  - For customer service, the nickname is the customer service\'s name.  - For buyers, the nickname is the buyer\'s nickname on TikTok.  You can set the nicknames for shops and customer service agents on Seller Center.  
    */
    'nickname'?: string;
    /**
    * Sender\'s role. Possible enumerations: - `BUYER` - `SHOP` - `CUSTOMER_SERVICE` - `SYSTEM` - `ROBOT` For `SYSTEM` and `ROBOT` role, the value of `im_user_id`, `nickname`, and `avatar` are the same as those of the `SHOP` role.
    */
    'role'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "imUserId",
            "baseName": "im_user_id",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponseDataConversationsLatestMessageSender.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetConversationsResponseDataConversationsParticipants.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309GetConversationsResponseDataConversationsParticipants {
    /**
    * Participant\'s avatar URL. 
    */
    'avatar'?: string;
    /**
    * Which platform is the buyer from.  This field will only be returned when the role is `BUYER` and the region is Indonesia. Possible enumerations: - TIKTOK_SHOP - TOKOPEDIA You cannot send platform-specific content to the buyer from a different platform. For example, when you send a product card to the Tokopedia buyer, you must ensure the product is listed on Tokopedia.
    */
    'buyerPlatform'?: string;
    /**
    * Participant\'s ID, in IM system. This ID is used in IM system and can not be used to query orders. To query orders, use `user_id` instead.
    */
    'imUserId'?: string;
    /**
    * Participant\'s nickname.
    */
    'nickname'?: string;
    /**
    * Participant\'s role. Possible enumerations: - `BUYER` - `SHOP` - `CUSTOMER_SERVICE`
    */
    'role'?: string;
    /**
    * Participant\'s ID.
    */
    'userId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "buyerPlatform",
            "baseName": "buyer_platform",
            "type": "string"
        },
        {
            "name": "imUserId",
            "baseName": "im_user_id",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309GetConversationsResponseDataConversationsParticipants.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ReadMessageResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309ReadMessageResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309ReadMessageResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/SendMessageRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309SendMessageRequestBody {
    /**
    * Message content, in JSON serialized string.  Examples of content for each type of message are listed below: ​ - TEXT: {     \"content\": \"hi, I want to get refunded.\" } (Note: Max 2000 characters. Do not use sensitive words that violate TikTok Shop terms & policies.)  - VIDEO {     \"vid\": \"v10394g5000cd499vc7og65mqn3r3dg0\" }  - LOGISTICS_CARD {     \"order_id\": \"580874485811283206\",     \"package_id\": \"123456\"  // Optional  (recommended for one order with multiple packages; not required for one order with one package) } ​ - PRODUCT_CARD {     \"product_id\": \"7494560109732334265\" } ​ - ORDER_CARD: {     \"order_id\": \"7494560109732334267\" }  - RETURN_REFUND_CARD: {     \"order_id\": \"7494560109732334267\",     \"sku_id\": \"7494560109732363423\" } Note: The order of the RETURN_REFUND_CARD to send must meet after-sale conditions. To check the eligibility, use [Get Aftersale Eligibility](650ab645c16ffe02b8f2e1c1). ​ - IMAGE: {     \"url\":\"https://p16-oec-va.ibyteimg.com/tos-maliva-i-o3syd03w52-us/2ca53c34ad8443e6b39f4e0153d3aed4~tplv-o3syd03w52-origin-image.image?from=1320446476\",     \"width\": 1280,     \"height\": 720 }  Note: You can get the value of `url` by calling [Upload Buyer Messages Image](650a599d0fcef602bf2a1dc8).  - COUPON_CARD: {     \"coupon_id\": \"7262992004278206762\" } Note: Coupons that can be sent in  a message must meet all the following conditions: 1. `display_type==CHAT` or `display_type==REGULAR` 2. `status==ONGOING` 3. `creation_source==SELLER_CENTER` 4. `target_buyer_segment!=REPEAT_CUSTOMERS`
    */
    'content'?: string;
    /**
    * Message type. Possible enumerations: - `TEXT` - `IMAGE` - `VIDEO` - `PRODUCT_CARD` - `ORDER_CARD` - `RETURN_REFUND_CARD` - `COUPON_CARD` - `LOGISTICS_CARD`
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309SendMessageRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/SendMessageResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309SendMessageResponseData } from './SendMessageResponseData';

export class CustomerService202309SendMessageResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309SendMessageResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309SendMessageResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309SendMessageResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/SendMessageResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309SendMessageResponseData {
    /**
    * Message ID
    */
    'messageId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309SendMessageResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/UpdateAgentSettingsRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309UpdateAgentSettingsRequestBody {
    /**
    * If true, the agent will receive auto-assigned chats. The agent can manually select chats to respond.  If false, the agent will receive manually assigned chats only. When using IM API, we recommend setting this field to true.
    */
    'canAcceptChat'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canAcceptChat",
            "baseName": "can_accept_chat",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309UpdateAgentSettingsRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/UpdateAgentSettingsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309UpdateAgentSettingsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: object;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309UpdateAgentSettingsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/UploadBuyerMessagesImageResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202309UploadBuyerMessagesImageResponseData } from './UploadBuyerMessagesImageResponseData';

export class CustomerService202309UploadBuyerMessagesImageResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202309UploadBuyerMessagesImageResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309UploadBuyerMessagesImageResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309UploadBuyerMessagesImageResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/UploadBuyerMessagesImageResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309UploadBuyerMessagesImageResponseData {
    /**
    * Image height
    */
    'height'?: number;
    /**
    * Image URL 
    */
    'url'?: string;
    /**
    * Image width
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309UploadBuyerMessagesImageResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetConversationResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202601GetConversationResponseData } from './GetConversationResponseData';

export class CustomerService202601GetConversationResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202601GetConversationResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202601GetConversationResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202601GetConversationResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetConversationResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202601GetConversationResponseDataConversation } from './GetConversationResponseDataConversation';

export class CustomerService202601GetConversationResponseData {
    'conversation'?: CustomerService202601GetConversationResponseDataConversation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conversation",
            "baseName": "conversation",
            "type": "CustomerService202601GetConversationResponseDataConversation"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202601GetConversationResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetConversationResponseDataConversation.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202601GetConversationResponseDataConversationParticipants } from './GetConversationResponseDataConversationParticipants';

export class CustomerService202601GetConversationResponseDataConversation {
    /**
    * Unix timestamp when the conversation was created. In seconds.
    */
    'createTime'?: number;
    /**
    * Current session id.
    */
    'curSessionId'?: string;
    /**
    * Conversation ID
    */
    'id'?: string;
    /**
    * Number of participants in the conversation. - If there has been no customer service agent in the conversation, the value is `2`: the shop and the buyer; - Otherwise, the value is `3`: the shop, the buyer, and the customer service agent.
    */
    'participantCount'?: number;
    /**
    * Conversation participants.
    */
    'participants'?: Array<CustomerService202601GetConversationResponseDataConversationParticipants>;
    /**
    * Number of messages unread by the customer service agent.
    */
    'unreadCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "curSessionId",
            "baseName": "cur_session_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "participantCount",
            "baseName": "participant_count",
            "type": "number"
        },
        {
            "name": "participants",
            "baseName": "participants",
            "type": "Array<CustomerService202601GetConversationResponseDataConversationParticipants>"
        },
        {
            "name": "unreadCount",
            "baseName": "unread_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202601GetConversationResponseDataConversation.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetConversationResponseDataConversationParticipants.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202601GetConversationResponseDataConversationParticipants {
    /**
    * Participant\'s avatar URL.
    */
    'avatar'?: string;
    /**
    * Participant\'s ID, in IM system. This ID is used in IM system and can not be used to query orders. To query orders, use `user_id` instead.
    */
    'imUserId'?: string;
    /**
    * Participant\'s nickname.
    */
    'nickname'?: string;
    /**
    * Which platform is the buyer from. This field will only be returned when the role is `BUYER` and the region is Indonesia. Possible enumerations: - TIKTOK_SHOP - TOKOPEDIA You cannot send platform-specific content to the buyer from a different platform. For example, when you send a product card to the Tokopedia buyer, you must ensure the product is listed on Tokopedia.
    */
    'platform'?: string;
    /**
    * Participant\'s role. Possible enumerations: - `BUYER` - `SHOP` - `CUSTOMER_SERVICE`
    */
    'role'?: string;
    /**
    * Participant\'s ID.
    */
    'userId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "imUserId",
            "baseName": "im_user_id",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202601GetConversationResponseDataConversationParticipants.attributeTypeMap;
    }
}



// ==== SOURCE: V202602/SearchSessionsRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202602SearchSessionsRequestBody {
    /**
    * Return sessions whose begin_time is greater than or equal to the specified time. Only data from the last 90 days is supported.
    */
    'beginTimeGe'?: number;
    /**
    * Return sessions whose begin_time is less than the specified timestamp.
    */
    'beginTimeLt'?: number;
    /**
    * Buyer\'s nickname.
    */
    'buyerNickname'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "beginTimeGe",
            "baseName": "begin_time_ge",
            "type": "number"
        },
        {
            "name": "beginTimeLt",
            "baseName": "begin_time_lt",
            "type": "number"
        },
        {
            "name": "buyerNickname",
            "baseName": "buyer_nickname",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202602SearchSessionsRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202602/SearchSessionsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202602SearchSessionsResponseData } from './SearchSessionsResponseData';

export class CustomerService202602SearchSessionsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: CustomerService202602SearchSessionsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202602SearchSessionsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202602SearchSessionsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202602/SearchSessionsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { CustomerService202602SearchSessionsResponseDataSessions } from './SearchSessionsResponseDataSessions';

export class CustomerService202602SearchSessionsResponseData {
    /**
    * If there is no more record, this field will be \"\"(empty string).
    */
    'nextPageToken'?: string;
    /**
    * Session info.
    */
    'sessions'?: Array<CustomerService202602SearchSessionsResponseDataSessions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "sessions",
            "baseName": "sessions",
            "type": "Array<CustomerService202602SearchSessionsResponseDataSessions>"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202602SearchSessionsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202602/SearchSessionsResponseDataSessions.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202602SearchSessionsResponseDataSessions {
    /**
    * The timestamp when the session began.
    */
    'beginTime'?: number;
    /**
    * Buyer\'s nickname.
    */
    'buyerNickname'?: string;
    /**
    * AfterSale/Logistics/Presale
    */
    'chatTags'?: Array<string>;
    /**
    * Conversation id.
    */
    'conversationId'?: string;
    /**
    * Reason provided by the buyer for a low satisfaction rating. The language of the reason is determined by the locale request parameter.
    */
    'dissatisfactionReason'?: string;
    /**
    * The timestamp when the session end.
    */
    'endTime'?: number;
    /**
    * Indicates whether the first response exceeded the expected response time or SLA.
    */
    'firstResponseLate'?: boolean;
    /**
    * Time elapsed in seconds between when the buyer sends the first message and when the seller sends the first response.
    */
    'firstResponseTime'?: number;
    /**
    * Session id.
    */
    'id'?: string;
    /**
    * Customer satisfaction rating for the session (e.g., 1–5). Higher scores indicate greater satisfaction.
    */
    'satisfactionScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "beginTime",
            "baseName": "begin_time",
            "type": "number"
        },
        {
            "name": "buyerNickname",
            "baseName": "buyer_nickname",
            "type": "string"
        },
        {
            "name": "chatTags",
            "baseName": "chat_tags",
            "type": "Array<string>"
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string"
        },
        {
            "name": "dissatisfactionReason",
            "baseName": "dissatisfaction_reason",
            "type": "string"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "firstResponseLate",
            "baseName": "first_response_late",
            "type": "boolean"
        },
        {
            "name": "firstResponseTime",
            "baseName": "first_response_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "satisfactionScore",
            "baseName": "satisfaction_score",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202602SearchSessionsResponseDataSessions.attributeTypeMap;
    }
}


