// Consolidated TypeScript model definitions for module: dataReconciliation
// Merged from 24 source files.


// ==== SOURCE: V202309/OrderStatusDataExchangeRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeRequestBodyOrders } from './OrderStatusDataExchangeRequestBodyOrders';

export class DataReconciliation202309OrderStatusDataExchangeRequestBody {
    /**
    * The exchange order list
    */
    'orders'?: Array<DataReconciliation202309OrderStatusDataExchangeRequestBodyOrders>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<DataReconciliation202309OrderStatusDataExchangeRequestBodyOrders>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeRequestBodyOrders.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeRequestBodyOrdersPackages } from './OrderStatusDataExchangeRequestBodyOrdersPackages';

export class DataReconciliation202309OrderStatusDataExchangeRequestBodyOrders {
    /**
    * If \'channel_type\' is SHOPIFY,the financial status enumeration, data not in the following enumeration will return an error. shopify financial status: PENDING AUTHORIZED OVERDUE EXPIRING EXPIRED PAID REFUNDED PARTIALLY_REFUNDED PARTIALLY_PAID VOIDED UNPAID
    */
    'channelFinancialStatus'?: string;
    /**
    * If \'channel_type\' is SHOPIFY,the fulfillment status enumeration, data not in the following enumeration will return an error.  Shopify fulfillment status: FULFILLED ON_HOLD PARTIALLY_FULFILLED UNFULFILLED SCHEDULED
    */
    'channelFulfillmentStatus'?: string;
    /**
    * Direct To Consumer System order id
    */
    'channelOrderId'?: string;
    /**
    * The order status enumeration under the corresponding \'channel_type\', and an error will be returned for data outside the enumeration under the \'channel_type\'. The correspondence between \'channel_type\' and order status is as follows.  1. channel_type is \'SHOPIFY\' correspondence order status: OPEN ARCHIVED CANCELED  2. channel_type is \'WOOCOMMERCE\' correspondence order status: PENDING ON_HOLD PROCESSING COMPLETED REFUNDED  3. channel_type is \'BIGCOMMERCE\' correspondence order status: AWAITING_PAYMENT AWAITING_FULFILLMENT AWATING_SHIPMENT PARTIALLY_SHIPPED INCOMPLETE MANUAL_VERIFICATION_REQUIRED SHIPPED CANCELLED REFUND PENDING  4. channel_type is \'MAGENTO\' correspondence order status: NEW PROCESSING PENDING COMPLETE CLOSED PENDING_PAYMENT ON_HOLD
    */
    'channelOrderStatus'?: string;
    /**
    * The update timestamp of the order on the DTC, not the current api call time. Unit: second, the length must be 10. The value must less than current timestamp.
    */
    'channelOrderUpdateTime'?: string;
    /**
    * DTC channel type enumeration, data not in the following enumeration will return an error: SHOPIFY WOOCOMMERCE BIGCOMMERCE MAGENTO
    */
    'channelType'?: string;
    /**
    * The reason of that there is no matched order in channel platform 
    */
    'notExistReason'?: string;
    /**
    * Tiktok shop\'s order id, must be a pure numeric string.
    */
    'orderId'?: string;
    /**
    * the package information list of order
    */
    'packages'?: Array<DataReconciliation202309OrderStatusDataExchangeRequestBodyOrdersPackages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelFinancialStatus",
            "baseName": "channel_financial_status",
            "type": "string"
        },
        {
            "name": "channelFulfillmentStatus",
            "baseName": "channel_fulfillment_status",
            "type": "string"
        },
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelOrderStatus",
            "baseName": "channel_order_status",
            "type": "string"
        },
        {
            "name": "channelOrderUpdateTime",
            "baseName": "channel_order_update_time",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "notExistReason",
            "baseName": "not_exist_reason",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<DataReconciliation202309OrderStatusDataExchangeRequestBodyOrdersPackages>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeRequestBodyOrders.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeRequestBodyOrdersPackages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202309OrderStatusDataExchangeRequestBodyOrdersPackages {
    /**
    * The provider name of tracking info
    */
    'logisticsProviderName'?: string;
    /**
    * The tracking corresponding Tiktok shop package id
    */
    'packageId'?: string;
    /**
    * Tracking number of tracking info
    */
    'trackingNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "logisticsProviderName",
            "baseName": "logistics_provider_name",
            "type": "string"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeRequestBodyOrdersPackages.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeResponseData } from './OrderStatusDataExchangeResponseData';

export class DataReconciliation202309OrderStatusDataExchangeResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: DataReconciliation202309OrderStatusDataExchangeResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DataReconciliation202309OrderStatusDataExchangeResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeResponseDataErrors } from './OrderStatusDataExchangeResponseDataErrors';

export class DataReconciliation202309OrderStatusDataExchangeResponseData {
    /**
    * The list of errors that occurred from executing the mutation, one failed order one element
    */
    'errors'?: Array<DataReconciliation202309OrderStatusDataExchangeResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<DataReconciliation202309OrderStatusDataExchangeResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeResponseDataErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail } from './OrderStatusDataExchangeResponseDataErrorsDetail';

export class DataReconciliation202309OrderStatusDataExchangeResponseDataErrors {
    /**
    * Integartion err code
    */
    'code'?: string;
    'detail'?: DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail;
    /**
    * Integartion err message
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseDataErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeResponseDataErrorsDetail.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors } from './OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors';

export class DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail {
    /**
    * Failed channel order id
    */
    'channelOrderId'?: string;
    /**
    * Failed channel type
    */
    'channelType'?: string;
    /**
    * Failed order reasons
    */
    'extraErrors'?: Array<DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors>;
    /**
    * Failed Tiktok Shop order id
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "extraErrors",
            "baseName": "extra_errors",
            "type": "Array<DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetail.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors {
    /**
    * Business err code
    */
    'code'?: string;
    /**
    * Business err message
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202309OrderStatusDataExchangeResponseDataErrorsDetailExtraErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrders } from './QualityFactoryOrderDataImportAPIRequestBodyOrders';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBody {
    /**
    * The exchange order list 
    */
    'orders'?: Array<DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrders>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrders>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIRequestBodyOrders.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages } from './QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrders {
    /**
    * If \'channel_type\' is SHOPIFY,the financial status enumeration, data not in the following enumeration will return an error. shopify financial status: PENDING AUTHORIZED OVERDUE EXPIRING EXPIRED PAID REFUNDED PARTIALLY_REFUNDED PARTIALLY_PAID VOIDED UNPAID
    */
    'channelFinancialStatus'?: string;
    /**
    * If \'channel_type\' is SHOPIFY,the fulfillment status enumeration, data not in the following enumeration will return an error.  Shopify fulfillment status: FULFILLED ON_HOLD PARTIALLY_FULFILLED UNFULFILLED SCHEDULED
    */
    'channelFulfillmentStatus'?: string;
    /**
    * Direct To Consumer System order id 
    */
    'channelOrderId'?: string;
    /**
    * The order status enumeration under the corresponding \'channel_type\', and an error will be returned for data outside the enumeration under the \'channel_type\'. The correspondence between \'channel_type\' and order status is as follows.  1. channel_type is \'SHOPIFY\' correspondence order status: OPEN ARCHIVED CANCELED  2. channel_type is \'WOOCOMMERCE\' correspondence order status: PENDING ON_HOLD PROCESSING COMPLETED REFUNDED  3. channel_type is \'BIGCOMMERCE\' correspondence order status: AWAITING_PAYMENT AWAITING_FULFILLMENT AWATING_SHIPMENT PARTIALLY_SHIPPED INCOMPLETE MANUAL_VERIFICATION_REQUIRED SHIPPED CANCELLED REFUND PENDING  4. channel_type is \'MAGENTO\' correspondence order status: NEW PROCESSING PENDING COMPLETE CLOSED PENDING_PAYMENT ON_HOLD
    */
    'channelOrderStatus'?: string;
    /**
    * The update timestamp of the order on the DTC, not the current api call time. Unit: second, the length must be 10. The value must less than current timestamp.
    */
    'channelOrderUpdateTime'?: string;
    /**
    * DTC channel type enumeration, data not in the following enumeration will return an error: SHOPIFY WOOCOMMERCE BIGCOMMERCE MAGENTO
    */
    'channelType'?: string;
    /**
    * Developers must use one of the Reason Codes listed within your API request parameters. If you don\'t use one of the ENUMs, the API will return an error. Refer to this doc for a list of possible reason codes:  https://partner.tiktokshop.com/docv2/page/660bf931cf5cc502e03007ca#Back%20To%20Top
    */
    'issueReason'?: string;
    /**
    * Tiktok shop\'s order id, must be a pure numeric string.
    */
    'orderId'?: string;
    /**
    * the package information list of order
    */
    'packages'?: Array<DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelFinancialStatus",
            "baseName": "channel_financial_status",
            "type": "string"
        },
        {
            "name": "channelFulfillmentStatus",
            "baseName": "channel_fulfillment_status",
            "type": "string"
        },
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelOrderStatus",
            "baseName": "channel_order_status",
            "type": "string"
        },
        {
            "name": "channelOrderUpdateTime",
            "baseName": "channel_order_update_time",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "issueReason",
            "baseName": "issue_reason",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrders.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages {
    /**
    * The tracking corresponding Tiktok shop package id 
    */
    'packageId'?: string;
    /**
    * The provider name of tracking info
    */
    'shippingProviderName'?: string;
    /**
    * Tracking number of tracking info 
    */
    'trackingNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData } from './QualityFactoryOrderDataImportAPIResponseData';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors } from './QualityFactoryOrderDataImportAPIResponseDataErrors';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData {
    /**
    * The list of errors that occurred from executing the mutation, one failed order one element
    */
    'errors'?: Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIResponseDataErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail } from './QualityFactoryOrderDataImportAPIResponseDataErrorsDetail';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors {
    /**
    * Integartion err code 
    */
    'code'?: string;
    'detail'?: DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail;
    /**
    * Integartion err message 
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors } from './QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail {
    /**
    * Failed channel order id 
    */
    'channelOrderId'?: string;
    /**
    * Failed channel type 
    */
    'channelType'?: string;
    /**
    * Failed order reasons
    */
    'extraErrors'?: Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors>;
    /**
    * Failed Tiktok Shop order id 
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "extraErrors",
            "baseName": "extra_errors",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.attributeTypeMap;
    }
}



// ==== SOURCE: V202401/QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors {
    /**
    * Business err code 
    */
    'code'?: string;
    /**
    * Business err message 
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders } from './QualityFactoryOrderDataImportAPIRequestBodyOrders';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody {
    /**
    * The exchange order list 
    */
    'orders'?: Array<DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIRequestBodyOrders.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages } from './QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders {
    /**
    * If \'channel_type\' is SHOPIFY,the financial status enumeration, data not in the following enumeration will return an error. shopify financial status: PENDING AUTHORIZED OVERDUE EXPIRING EXPIRED PAID REFUNDED PARTIALLY_REFUNDED PARTIALLY_PAID VOIDED UNPAID
    */
    'channelFinancialStatus'?: string;
    /**
    * If \'channel_type\' is SHOPIFY,the fulfillment status enumeration, data not in the following enumeration will return an error.  Shopify fulfillment status: FULFILLED ON_HOLD PARTIALLY_FULFILLED UNFULFILLED SCHEDULED
    */
    'channelFulfillmentStatus'?: string;
    /**
    * Direct To Consumer System order id 
    */
    'channelOrderId'?: string;
    /**
    * The order status enumeration under the corresponding \'channel_type\', and an error will be returned for data outside the enumeration under the \'channel_type\'. The correspondence between \'channel_type\' and order status is as follows.  1. channel_type is \'SHOPIFY\' correspondence order status: OPEN ARCHIVED CANCELED  2. channel_type is \'WOOCOMMERCE\' correspondence order status: PENDING ON_HOLD PROCESSING COMPLETED REFUNDED  3. channel_type is \'BIGCOMMERCE\' correspondence order status: AWAITING_PAYMENT AWAITING_FULFILLMENT AWATING_SHIPMENT PARTIALLY_SHIPPED INCOMPLETE MANUAL_VERIFICATION_REQUIRED SHIPPED CANCELLED REFUND PENDING  4. channel_type is \'MAGENTO\' correspondence order status: NEW PROCESSING PENDING COMPLETE CLOSED PENDING_PAYMENT ON_HOLD
    */
    'channelOrderStatus'?: string;
    /**
    * The update timestamp of the order on the DTC, not the current api call time. Unit: second, the length must be 10. The value must less than current timestamp.
    */
    'channelOrderUpdateTime'?: string;
    /**
    * DTC channel type enumeration, data not in the following enumeration will return an error: SHOPIFY WOOCOMMERCE BIGCOMMERCE MAGENTO
    */
    'channelType'?: string;
    /**
    * The reason of that there is no matched order in channel platform
    */
    'notExistReason'?: string;
    /**
    * Tiktok shop\'s order id, must be a pure numeric string.
    */
    'orderId'?: string;
    /**
    * the package information list of order
    */
    'packages'?: Array<DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelFinancialStatus",
            "baseName": "channel_financial_status",
            "type": "string"
        },
        {
            "name": "channelFulfillmentStatus",
            "baseName": "channel_fulfillment_status",
            "type": "string"
        },
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelOrderStatus",
            "baseName": "channel_order_status",
            "type": "string"
        },
        {
            "name": "channelOrderUpdateTime",
            "baseName": "channel_order_update_time",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "notExistReason",
            "baseName": "not_exist_reason",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrders.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages {
    /**
    * The tracking corresponding Tiktok shop package id 
    */
    'packageId'?: string;
    /**
    * The provider name of tracking info
    */
    'shippingProviderName'?: string;
    /**
    * Tracking number of tracking info 
    */
    'trackingNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData } from './QualityFactoryOrderDataImportAPIResponseData';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors } from './QualityFactoryOrderDataImportAPIResponseDataErrors';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData {
    /**
    * The list of errors that occurred from executing the mutation, one failed order one element
    */
    'errors'?: Array<DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIResponseDataErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetail } from './QualityFactoryOrderDataImportAPIResponseDataErrorsDetail';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors {
    /**
    * Integartion err code 
    */
    'code'?: string;
    'detail'?: DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetail;
    /**
    * Integartion err message 
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors } from './QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetail {
    /**
    * Failed channel order id 
    */
    'channelOrderId'?: string;
    /**
    * Failed channel type 
    */
    'channelType'?: string;
    /**
    * Failed order reasons
    */
    'extraErrors'?: Array<DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors>;
    /**
    * Failed Tiktok Shop order id 
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "extraErrors",
            "baseName": "extra_errors",
            "type": "Array<DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.attributeTypeMap;
    }
}



// ==== SOURCE: V202310/QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors {
    /**
    * Business err code 
    */
    'code'?: string;
    /**
    * Business err message 
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataReconciliation202310QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors.attributeTypeMap;
    }
}


