// Consolidated TypeScript model definitions for module: logistics
// Merged from 26 source files.


// ==== SOURCE: V202510/GetAvailableShippingTemplateRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateRequestBodyProductAttribute } from './GetAvailableShippingTemplateRequestBodyProductAttribute';

export class Logistics202510GetAvailableShippingTemplateRequestBody {
    'productAttribute'?: Logistics202510GetAvailableShippingTemplateRequestBodyProductAttribute;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productAttribute",
            "baseName": "product_attribute",
            "type": "Logistics202510GetAvailableShippingTemplateRequestBodyProductAttribute"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateRequestBodyProductAttribute.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeDimension } from './GetAvailableShippingTemplateRequestBodyProductAttributeDimension';
import { Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeWeight } from './GetAvailableShippingTemplateRequestBodyProductAttributeWeight';

export class Logistics202510GetAvailableShippingTemplateRequestBodyProductAttribute {
    'dimension'?: Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeDimension;
    'weight'?: Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeWeight;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeDimension"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeWeight"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateRequestBodyProductAttribute.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateRequestBodyProductAttributeDimension.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeDimension {
    /**
    * The height of the product
    */
    'height'?: string;
    /**
    * The length of the product
    */
    'length'?: string;
    /**
    * 1: centimeter 2:inch 3:foot 4:millimeter 5:meter
    */
    'unit'?: number;
    /**
    * The width of the product
    */
    'width'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeDimension.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateRequestBodyProductAttributeWeight.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeWeight {
    /**
    * 1:gram 2:pound 3:ounce 4:kilogram
    */
    'unit'?: number;
    /**
    * The weight of product
    */
    'weight'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "number"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateRequestBodyProductAttributeWeight.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseData } from './GetAvailableShippingTemplateResponseData';

export class Logistics202510GetAvailableShippingTemplateResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Logistics202510GetAvailableShippingTemplateResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Logistics202510GetAvailableShippingTemplateResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplates } from './GetAvailableShippingTemplateResponseDataTemplates';

export class Logistics202510GetAvailableShippingTemplateResponseData {
    /**
    * All the seller\'s template
    */
    'templates'?: Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "templates",
            "baseName": "templates",
            "type": "Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplates>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponseDataTemplates.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason } from './GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplatesTemplate } from './GetAvailableShippingTemplateResponseDataTemplatesTemplate';

export class Logistics202510GetAvailableShippingTemplateResponseDataTemplates {
    /**
    * If service_unreachable_reason is not empty, it will contain a \"reason\" why this template is not usable.  If service_unreachable_reason is empty, then template is usable
    */
    'serviceUnreachableReason'?: Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason>;
    'template'?: Logistics202510GetAvailableShippingTemplateResponseDataTemplatesTemplate;
    /**
    * Whether the template is available
    */
    'templateIsAvailable'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serviceUnreachableReason",
            "baseName": "service_unreachable_reason",
            "type": "Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason>"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Logistics202510GetAvailableShippingTemplateResponseDataTemplatesTemplate"
        },
        {
            "name": "templateIsAvailable",
            "baseName": "template_is_available",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseDataTemplates.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason } from './GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason';

export class Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason {
    /**
    * Contains the reason why this template is not usable
    */
    'filterReason'?: Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason>;
    /**
    * Id of the service
    */
    'serviceId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterReason",
            "baseName": "filter_reason",
            "type": "Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason>"
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason {
    /**
    * 1 for length filter 2 for width filter 3 for height filter 4 for weight filter 9 for service mode filter 11 for service filter
    */
    'filterType'?: string;
    /**
    * Detailed reason for unreachable 
    */
    'reason'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterType",
            "baseName": "filter_type",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason.attributeTypeMap;
    }
}



// ==== SOURCE: V202510/GetAvailableShippingTemplateResponseDataTemplatesTemplate.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202510GetAvailableShippingTemplateResponseDataTemplatesTemplate {
    /**
    * Is default template or not
    */
    'isDefault'?: boolean;
    /**
    * The template_id
    */
    'templateId'?: string;
    /**
    * The template name
    */
    'templateName'?: string;
    /**
    * 1 for shipping by platform template 2 for shipping by seller template
    */
    'templateParty'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isDefault",
            "baseName": "is_default",
            "type": "boolean"
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string"
        },
        {
            "name": "templateName",
            "baseName": "template_name",
            "type": "string"
        },
        {
            "name": "templateParty",
            "baseName": "template_party",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseDataTemplatesTemplate.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetGlobalSellerWarehouseResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetGlobalSellerWarehouseResponseData } from './GetGlobalSellerWarehouseResponseData';

export class Logistics202309GetGlobalSellerWarehouseResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Logistics202309GetGlobalSellerWarehouseResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Logistics202309GetGlobalSellerWarehouseResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetGlobalSellerWarehouseResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetGlobalSellerWarehouseResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses } from './GetGlobalSellerWarehouseResponseDataGlobalWarehouses';

export class Logistics202309GetGlobalSellerWarehouseResponseData {
    /**
    * Global warehouse information.
    */
    'globalWarehouses'?: Array<Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "globalWarehouses",
            "baseName": "global_warehouses",
            "type": "Array<Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetGlobalSellerWarehouseResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetGlobalSellerWarehouseResponseDataGlobalWarehouses.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses {
    /**
    * Global warehouse ID, a unique and immutable primary key, used for all global warehouse logistics.
    */
    'id'?: string;
    /**
    * Global warehouse name. This name is not unique across the TikTok Shop system.
    */
    'name'?: string;
    /**
    * Possible values: - SELLER: Warehouse owned by the seller.  - PLATFORM_COOPERATION: Warehouse owned by TikTok Shop.  
    */
    'ownership'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ownership",
            "baseName": "ownership",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShippingProvidersResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetShippingProvidersResponseData } from './GetShippingProvidersResponseData';

export class Logistics202309GetShippingProvidersResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Logistics202309GetShippingProvidersResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Logistics202309GetShippingProvidersResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetShippingProvidersResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShippingProvidersResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetShippingProvidersResponseDataShippingProviders } from './GetShippingProvidersResponseDataShippingProviders';

export class Logistics202309GetShippingProvidersResponseData {
    /**
    * shipping provider list
    */
    'shippingProviders'?: Array<Logistics202309GetShippingProvidersResponseDataShippingProviders>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shippingProviders",
            "baseName": "shipping_providers",
            "type": "Array<Logistics202309GetShippingProvidersResponseDataShippingProviders>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetShippingProvidersResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetShippingProvidersResponseDataShippingProviders.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202309GetShippingProvidersResponseDataShippingProviders {
    /**
    * shipping provider id
    */
    'id'?: string;
    /**
    * shipping provider name
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetShippingProvidersResponseDataShippingProviders.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseDeliveryOptionsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseDeliveryOptionsResponseData } from './GetWarehouseDeliveryOptionsResponseData';

export class Logistics202309GetWarehouseDeliveryOptionsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Logistics202309GetWarehouseDeliveryOptionsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Logistics202309GetWarehouseDeliveryOptionsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseDeliveryOptionsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseDeliveryOptionsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptions } from './GetWarehouseDeliveryOptionsResponseDataDeliveryOptions';

export class Logistics202309GetWarehouseDeliveryOptionsResponseData {
    /**
    * List of deliver options available through the seller\'s warehouse, and the respective carriers and attribute restrictions depending on the commodity.
    */
    'deliveryOptions'?: Array<Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deliveryOptions",
            "baseName": "delivery_options",
            "type": "Array<Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptions>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseDeliveryOptionsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseDeliveryOptionsResponseDataDeliveryOptions.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit } from './GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit';
import { Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit } from './GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit';

export class Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptions {
    /**
    * Delivery option description.
    */
    'description'?: string;
    'dimensionLimit'?: Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit;
    /**
    * Delivery option ID.
    */
    'id'?: string;
    /**
    * Delivery option name.
    */
    'name'?: string;
    /**
    * The platform on which the delivery option is available Possible values: - TIKTOK_SHOP - TOKOPEDIA
    */
    'platform'?: Array<string>;
    /**
    * Delivery option type. This is an enumerated type with values: - STANDARD - EXPRESS - ECONOMY - SEND_BY_SELLER
    */
    'type'?: string;
    'weightLimit'?: Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "dimensionLimit",
            "baseName": "dimension_limit",
            "type": "Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Array<string>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "weightLimit",
            "baseName": "weight_limit",
            "type": "Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptions.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit {
    /**
    * Maximum height limit.
    */
    'maxHeight'?: number;
    /**
    * Maximum length limit.
    */
    'maxLength'?: number;
    /**
    * Maximum width limit.
    */
    'maxWidth'?: number;
    /**
    * The unit of measurement for the dimensions, with possible values: - CM - INCH
    */
    'unit'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxHeight",
            "baseName": "max_height",
            "type": "number"
        },
        {
            "name": "maxLength",
            "baseName": "max_length",
            "type": "number"
        },
        {
            "name": "maxWidth",
            "baseName": "max_width",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit {
    /**
    * Maximum weight limit.
    */
    'maxWeight'?: number;
    /**
    * Minimum weight limit.
    */
    'minWeight'?: number;
    /**
    * The unit of measurement for the weight, with possible values: - GRAM - POUND
    */
    'unit'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxWeight",
            "baseName": "max_weight",
            "type": "number"
        },
        {
            "name": "minWeight",
            "baseName": "min_weight",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseListResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseListResponseData } from './GetWarehouseListResponseData';

export class Logistics202309GetWarehouseListResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Logistics202309GetWarehouseListResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Logistics202309GetWarehouseListResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseListResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseListResponseDataWarehouses } from './GetWarehouseListResponseDataWarehouses';

export class Logistics202309GetWarehouseListResponseData {
    /**
    * All the warehouses associated with the seller.
    */
    'warehouses'?: Array<Logistics202309GetWarehouseListResponseDataWarehouses>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "warehouses",
            "baseName": "warehouses",
            "type": "Array<Logistics202309GetWarehouseListResponseDataWarehouses>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseListResponseDataWarehouses.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseListResponseDataWarehousesAddress } from './GetWarehouseListResponseDataWarehousesAddress';

export class Logistics202309GetWarehouseListResponseDataWarehouses {
    'address'?: Logistics202309GetWarehouseListResponseDataWarehousesAddress;
    /**
    * Possible values: - ENABLED: All products in stock are available for sale. - DISABLED: All products in stock are unavailable for sale.  - RESTRICTED: The warehouse is either on \"holiday mode\" or \"order limit mode.\" All products in stock are unavailable for sale. -Holiday mode: When the seller cannot fulfill an order from a warehouse, the seller can turn on holiday mode for the warehouse in seller center.  - Order limit mode: When the seller violates TikTok Shop policies, TikTok Shop will limit the order volume that can be fulfilled by a warehouse.
    */
    'effectStatus'?: string;
    /**
    * The warehouse entity ID, used to associate physical information of a warehouse, different warehouses may be associated with the same entity.
    */
    'entityId'?: string;
    /**
    * The warehouse ID, a unique and immutable primary key, used for all warehouse logistics.
    */
    'id'?: string;
    /**
    * The default warehouse.  If a product is listed with no designated warehouse, the default warehouse will be used.
    */
    'isDefault'?: boolean;
    /**
    * Warehouse name. This name is not unique across the TikTok Shop system.
    */
    'name'?: string;
    /**
    * Possible values: - DOMESTIC_WAREHOUSE: The warehouse is in the same country as the target market and the seller. - CB_OVERSEA_WAREHOUSE: For cross-border sellers, a local warehouse in the target market.  - CB_DIRECT_SHIPPING_WAREHOUSE: For cross-border sellers, a warehouse in the seller\'s base country, e.g., Mainland China or Hong Kong.
    */
    'subType'?: string;
    /**
    * Possible values: - SALES_WAREHOUSE: Warehouse for shipping products.   - RETURN_WAREHOUSE: Warehouse for receiving returned products.  You can have the same warehouse for both shipping and receiving returns, but they will have different warehouse IDs with the same address.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "Logistics202309GetWarehouseListResponseDataWarehousesAddress"
        },
        {
            "name": "effectStatus",
            "baseName": "effect_status",
            "type": "string"
        },
        {
            "name": "entityId",
            "baseName": "entity_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isDefault",
            "baseName": "is_default",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "subType",
            "baseName": "sub_type",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponseDataWarehouses.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseListResponseDataWarehousesAddress.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation } from './GetWarehouseListResponseDataWarehousesAddressGeolocation';

export class Logistics202309GetWarehouseListResponseDataWarehousesAddress {
    /**
    * The first line of the warehouse address, like street name and street number. Note:  - For Brazilian market, this represents the neighborhood or district. - For the JP market, this represents the district (Chome), block (Banchi), building number (Go).
    */
    'addressLine1'?: string;
    /**
    * The second line of the warehouse address, like flat, apartment, or suit. Note: For the Brazilian market, this represents the street name.
    */
    'addressLine2'?: string;
    /**
    * This represents the street number. If it\'s `s/n`, it means null. Note: Available only in the Brazilian market.
    */
    'addressLine3'?: string;
    /**
    * This represents supplement information, like flat, apartment, or suit (optional). Note: Available only in the Brazilian market.
    */
    'addressLine4'?: string;
    /**
    * Warehouse city.
    */
    'city'?: string;
    /**
    * Warehouse contact person name.
    */
    'contactPerson'?: string;
    /**
    * Warehouse district.
    */
    'distict'?: string;
    /**
    * Kanji first name Applicable only for the JP market.
    */
    'firstName'?: string;
    /**
    * Hiragana or Katakana first name Applicable only for the JP market.
    */
    'firstNameLocalScript'?: string;
    /**
    * The combined warehouse address, including the street address and other address information such as apartment number, building, floor..etc (optional)
    */
    'fullAddress'?: string;
    'geolocation'?: Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation;
    /**
    * Kanji last name Applicable only for the JP market.
    */
    'lastName'?: string;
    /**
    * Hiragana or Katakana last name Applicable only for the JP market.
    */
    'lastNameLocalScript'?: string;
    /**
    * Warehouse phone number.
    */
    'phoneNumber'?: string;
    /**
    * Warehouse address postal code (also known as zip code)
    */
    'postalCode'?: string;
    /**
    * Warehouse region.
    */
    'region'?: string;
    /**
    * Warehouse region code.
    */
    'regionCode'?: string;
    /**
    * Warehouse state or province.
    */
    'state'?: string;
    /**
    * Warehouse town.
    */
    'town'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addressLine1",
            "baseName": "address_line1",
            "type": "string"
        },
        {
            "name": "addressLine2",
            "baseName": "address_line2",
            "type": "string"
        },
        {
            "name": "addressLine3",
            "baseName": "address_line3",
            "type": "string"
        },
        {
            "name": "addressLine4",
            "baseName": "address_line4",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "contactPerson",
            "baseName": "contact_person",
            "type": "string"
        },
        {
            "name": "distict",
            "baseName": "distict",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "firstNameLocalScript",
            "baseName": "first_name_local_script",
            "type": "string"
        },
        {
            "name": "fullAddress",
            "baseName": "full_address",
            "type": "string"
        },
        {
            "name": "geolocation",
            "baseName": "geolocation",
            "type": "Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "lastNameLocalScript",
            "baseName": "last_name_local_script",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "regionCode",
            "baseName": "region_code",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "town",
            "baseName": "town",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponseDataWarehousesAddress.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetWarehouseListResponseDataWarehousesAddressGeolocation.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation {
    /**
    * The latitude of the address.
    */
    'latitude'?: string;
    /**
    * The longitude of the address.
    */
    'longitude'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation.attributeTypeMap;
    }
}


