// Consolidated TypeScript model definitions for module: open
// Merged from 3 source files.


// ==== SOURCE: V202512/UploadFileInitRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Open202512UploadFileInitRequestBody {
    /**
    * file name
    */
    'fileName'?: string;
    /**
    * file size, bytes
    */
    'fileSize'?: number;
    /**
    * Supported file types. current only support video
    */
    'fileType'?: string;
    /**
    * After the video is uploaded, use this interface to bind the video resource to the specific material 
    */
    'targetPath'?: string;
    /**
    * The total number of chunks.
    */
    'totalChunkCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string"
        },
        {
            "name": "fileSize",
            "baseName": "file_size",
            "type": "number"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string"
        },
        {
            "name": "targetPath",
            "baseName": "target_path",
            "type": "string"
        },
        {
            "name": "totalChunkCount",
            "baseName": "total_chunk_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Open202512UploadFileInitRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202512/UploadFileInitResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Open202512UploadFileInitResponseData } from './UploadFileInitResponseData';

export class Open202512UploadFileInitResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Open202512UploadFileInitResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Open202512UploadFileInitResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Open202512UploadFileInitResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202512/UploadFileInitResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Open202512UploadFileInitResponseData {
    /**
    * An identifier to upload a file
    */
    'uploadToken'?: string;
    /**
    * The URL provided by platform where the file can be uploaded.
    */
    'uploadUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uploadToken",
            "baseName": "upload_token",
            "type": "string"
        },
        {
            "name": "uploadUrl",
            "baseName": "upload_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Open202512UploadFileInitResponseData.attributeTypeMap;
    }
}


