// Consolidated TypeScript model definitions for module: seller
// Merged from 10 source files.


// ==== SOURCE: V202309/GetActiveShopsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202309GetActiveShopsResponseData } from './GetActiveShopsResponseData';

export class Seller202309GetActiveShopsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Seller202309GetActiveShopsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Seller202309GetActiveShopsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202309GetActiveShopsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetActiveShopsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202309GetActiveShopsResponseDataShops } from './GetActiveShopsResponseDataShops';

export class Seller202309GetActiveShopsResponseData {
    /**
    * The list of active shops that belong to the seller. Note: Local sellers only have 1 shop.
    */
    'shops'?: Array<Seller202309GetActiveShopsResponseDataShops>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shops",
            "baseName": "shops",
            "type": "Array<Seller202309GetActiveShopsResponseDataShops>"
        }    ];

    static getAttributeTypeMap() {
        return Seller202309GetActiveShopsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetActiveShopsResponseDataShops.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Seller202309GetActiveShopsResponseDataShops {
    /**
    * The ID of the shop.
    */
    'id'?: string;
    /**
    * The region of the shop.
    */
    'region'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202309GetActiveShopsResponseDataShops.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetSellerPermissionsResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202309GetSellerPermissionsResponseData } from './GetSellerPermissionsResponseData';

export class Seller202309GetSellerPermissionsResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Seller202309GetSellerPermissionsResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Seller202309GetSellerPermissionsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202309GetSellerPermissionsResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/GetSellerPermissionsResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Seller202309GetSellerPermissionsResponseData {
    /**
    * The list of cross-border operations that the seller is permitted to perform.  Possible values: - MANAGE_GLOBAL_PRODUCT: Indicates the seller is permitted to manage global products listed in TikTok Shops across multiple countries. If this is empty, it means the seller does not have permission to conduct cross-border operations.
    */
    'permissions'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Seller202309GetSellerPermissionsResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetShopGroupResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202601GetShopGroupResponseData } from './GetShopGroupResponseData';

export class Seller202601GetShopGroupResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: Seller202601GetShopGroupResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Seller202601GetShopGroupResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202601GetShopGroupResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetShopGroupResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202601GetShopGroupResponseDataShopGroupData } from './GetShopGroupResponseDataShopGroupData';

export class Seller202601GetShopGroupResponseData {
    'shopGroupData'?: Seller202601GetShopGroupResponseDataShopGroupData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shopGroupData",
            "baseName": "shop_group_data",
            "type": "Seller202601GetShopGroupResponseDataShopGroupData"
        }    ];

    static getAttributeTypeMap() {
        return Seller202601GetShopGroupResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetShopGroupResponseDataShopGroupData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Seller202601GetShopGroupResponseDataShopGroupDataShopGroup } from './GetShopGroupResponseDataShopGroupDataShopGroup';
import { Seller202601GetShopGroupResponseDataShopGroupDataShops } from './GetShopGroupResponseDataShopGroupDataShops';

export class Seller202601GetShopGroupResponseDataShopGroupData {
    'shopGroup'?: Seller202601GetShopGroupResponseDataShopGroupDataShopGroup;
    /**
    * Obtain the specific shop list
    */
    'shops'?: Array<Seller202601GetShopGroupResponseDataShopGroupDataShops>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shopGroup",
            "baseName": "shop_group",
            "type": "Seller202601GetShopGroupResponseDataShopGroupDataShopGroup"
        },
        {
            "name": "shops",
            "baseName": "shops",
            "type": "Array<Seller202601GetShopGroupResponseDataShopGroupDataShops>"
        }    ];

    static getAttributeTypeMap() {
        return Seller202601GetShopGroupResponseDataShopGroupData.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetShopGroupResponseDataShopGroupDataShopGroup.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Seller202601GetShopGroupResponseDataShopGroupDataShopGroup {
    /**
    * The unique name representing the product interoperability group
    */
    'shopGroupName'?: string;
    /**
    * Used to distinguish the creation source of product interoperability groups.  If it is a product interoperability group formed by a US local merchant opening an MX store, the enumeration value is: \'1 -> US_MX_ONBOARD\'  If it is a product interoperability group formed by a Chinese cross-border merchant opening an MX store, the enumeration value is \'2 -> GS_POP\'.
    */
    'source'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shopGroupName",
            "baseName": "shop_group_name",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202601GetShopGroupResponseDataShopGroupDataShopGroup.attributeTypeMap;
    }
}



// ==== SOURCE: V202601/GetShopGroupResponseDataShopGroupDataShops.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Seller202601GetShopGroupResponseDataShopGroupDataShops {
    /**
    * seller id 
    */
    'sellerId'?: string;
    /**
    * shop id
    */
    'shopId'?: string;
    /**
    * shop name
    */
    'shopName'?: string;
    /**
    * Region where the shop operates
    */
    'shopRegion'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sellerId",
            "baseName": "seller_id",
            "type": "string"
        },
        {
            "name": "shopId",
            "baseName": "shop_id",
            "type": "string"
        },
        {
            "name": "shopName",
            "baseName": "shop_name",
            "type": "string"
        },
        {
            "name": "shopRegion",
            "baseName": "shop_region",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Seller202601GetShopGroupResponseDataShopGroupDataShops.attributeTypeMap;
    }
}


