// Consolidated TypeScript model definitions for module: supplyChain
// Merged from 9 source files.


// ==== SOURCE: V202309/ConfirmPackageShipmentRequestBody.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { SupplyChain202309ConfirmPackageShipmentRequestBodyPackages } from './ConfirmPackageShipmentRequestBodyPackages';

export class SupplyChain202309ConfirmPackageShipmentRequestBody {
    /**
    * Package info list
    */
    'packages'?: Array<SupplyChain202309ConfirmPackageShipmentRequestBodyPackages>;
    /**
    * Warehouse provider ID, unique and provided by TikTok
    */
    'warehouseProviderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<SupplyChain202309ConfirmPackageShipmentRequestBodyPackages>"
        },
        {
            "name": "warehouseProviderId",
            "baseName": "warehouse_provider_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBody.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentRequestBodyPackages.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension } from './ConfirmPackageShipmentRequestBodyPackagesDimension';
import { SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus } from './ConfirmPackageShipmentRequestBodyPackagesSkus';
import { SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight } from './ConfirmPackageShipmentRequestBodyPackagesWeight';

export class SupplyChain202309ConfirmPackageShipmentRequestBodyPackages {
    /**
    * Time when warehouse receives the order (Unix timestamp in milliseconds)
    */
    'createTimeMillis'?: number;
    'dimension'?: SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension;
    /**
    * Time when the order is handed over to the shipping provider (Unix timestamp in milliseconds)
    */
    'handoverTimeMillis'?: number;
    /**
    * Package ID
    */
    'id'?: string;
    /**
    * Warehouse code
    */
    'providerWarehouseCode'?: string;
    /**
    * Warehouse name
    */
    'providerWarehouseName'?: string;
    /**
    * Time when the order is shipped out of the warehouse (Unix timestamp in milliseconds)
    */
    'shipTimeMillis'?: number;
    /**
    * Origin city name for the shipment
    */
    'shippingOriginCity'?: string;
    /**
    * Shipping service provider ID
    */
    'shippingProviderId'?: string;
    /**
    * Shipping service provider name
    */
    'shippingProviderName'?: string;
    /**
    * List of order SKUs 
    */
    'skus'?: Array<SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus>;
    /**
    * TikTok warehouse type  Possible values: - STANDARD: Standard warehouse that has not been specifically certified by TikTok  - TIKTOK_CERTIFIED_WAREHOUSE_FULFILLMENT: TikTok certified warehouse usually offering better service levels. Certified warehouses are required to meet fulfillment timeline standards set by TikTok
    */
    'tcwWarehouseType'?: string;
    /**
    * The warehouse time zone
    */
    'timeZone'?: string;
    /**
    * Tracking number
    */
    'trackingNumber'?: string;
    'weight'?: SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight;
    /**
    * Warehouse Management System order number
    */
    'wmsOrderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTimeMillis",
            "baseName": "create_time_millis",
            "type": "number"
        },
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension"
        },
        {
            "name": "handoverTimeMillis",
            "baseName": "handover_time_millis",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "providerWarehouseCode",
            "baseName": "provider_warehouse_code",
            "type": "string"
        },
        {
            "name": "providerWarehouseName",
            "baseName": "provider_warehouse_name",
            "type": "string"
        },
        {
            "name": "shipTimeMillis",
            "baseName": "ship_time_millis",
            "type": "number"
        },
        {
            "name": "shippingOriginCity",
            "baseName": "shipping_origin_city",
            "type": "string"
        },
        {
            "name": "shippingProviderId",
            "baseName": "shipping_provider_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus>"
        },
        {
            "name": "tcwWarehouseType",
            "baseName": "tcw_warehouse_type",
            "type": "string"
        },
        {
            "name": "timeZone",
            "baseName": "time_zone",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight"
        },
        {
            "name": "wmsOrderId",
            "baseName": "wms_order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackages.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentRequestBodyPackagesDimension.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension {
    /**
    * Package height value
    */
    'height'?: number;
    /**
    * Package length value
    */
    'length'?: number;
    /**
    * Package dimension unit Possible values: - METER - CENTIMETER - MILLIMETER - MICRON - FOOT - INCH
    */
    'unit'?: string;
    /**
    * Package width value
    */
    'width'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentRequestBodyPackagesSkus.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus {
    /**
    * TikTok Shop SKU ID
    */
    'id'?: string;
    /**
    * The quantity of each SKU
    */
    'quantity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentRequestBodyPackagesWeight.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight {
    /**
    * Package weight unit Possible values: - KILOGRAM - GRAM - MILLIGRAM - POUND - OUNCE
    */
    'unit'?: string;
    /**
    * Package weight value
    */
    'value'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentResponse.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { SupplyChain202309ConfirmPackageShipmentResponseData } from './ConfirmPackageShipmentResponseData';

export class SupplyChain202309ConfirmPackageShipmentResponse {
    /**
    * The success or failure status code returned in API response.
    */
    'code'?: number;
    'data'?: SupplyChain202309ConfirmPackageShipmentResponseData;
    /**
    * The success or failure messages returned in API response. Reasons of failure will be described in the message.
    */
    'message'?: string;
    /**
    * Request log.
    */
    'requestId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "SupplyChain202309ConfirmPackageShipmentResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentResponse.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentResponseData.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { SupplyChain202309ConfirmPackageShipmentResponseDataErrors } from './ConfirmPackageShipmentResponseDataErrors';

export class SupplyChain202309ConfirmPackageShipmentResponseData {
    /**
    * Error list
    */
    'errors'?: Array<SupplyChain202309ConfirmPackageShipmentResponseDataErrors>;
    /**
    * List of packages that have been successfully confirmed
    */
    'successPackages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SupplyChain202309ConfirmPackageShipmentResponseDataErrors>"
        },
        {
            "name": "successPackages",
            "baseName": "success_packages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentResponseData.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentResponseDataErrors.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail } from './ConfirmPackageShipmentResponseDataErrorsDetail';

export class SupplyChain202309ConfirmPackageShipmentResponseDataErrors {
    /**
    * Error code
    */
    'code'?: string;
    'detail'?: SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail;
    /**
    * Error message
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentResponseDataErrors.attributeTypeMap;
    }
}



// ==== SOURCE: V202309/ConfirmPackageShipmentResponseDataErrorsDetail.ts ====
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail {
    /**
    * Failed package ID
    */
    'packageId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail.attributeTypeMap;
    }
}


