/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202309ApproveReturnRequestBodyPartialRefund } from './ApproveReturnRequestBodyPartialRefund';

export class ReturnRefund202309ApproveReturnRequestBody {
    /**
    * **Optional**. Use this field only when decision is set to `APPROVE_RETURN`. If set to `true`, the seller issues a returnless refund, which means the buyer receives a full refund and keeps the item.
    */
    'buyerKeepItem'?: boolean;
    /**
    * Seller\'s decision for the return request, available values: - `APPROVE_REFUND`: seller approve a refund-only request - `APPROVE_RETURN`: seller approve the initial return-and-refund request - `APPROVE_RECEIVED_PACKAGE`: seller approve return-and-refund request after the buyer has already shipped or handed over the item. - `APPROVE_REPLACEMENT`: seller approve replacement request - `ISSUE_REPLACEMENT_REFUND`: seller decline the replacement request and directly refund the buyer instead. - `OFFER_PARTIAL_REFUND`: seller offers a partial refund amount to the buyer without requiring the item(s) to be returned. - `DIRECT_REFUND`: seller issues a returnless refund, meaning the buyer receives a full refund and keeps the item
    */
    'decision'?: string;
    'partialRefund'?: ReturnRefund202309ApproveReturnRequestBodyPartialRefund;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerKeepItem",
            "baseName": "buyer_keep_item",
            "type": "boolean"
        },
        {
            "name": "decision",
            "baseName": "decision",
            "type": "string"
        },
        {
            "name": "partialRefund",
            "baseName": "partial_refund",
            "type": "ReturnRefund202309ApproveReturnRequestBodyPartialRefund"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309ApproveReturnRequestBody.attributeTypeMap;
    }
}

