/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202309RejectReturnRequestBodyImages } from './RejectReturnRequestBodyImages';

export class ReturnRefund202309RejectReturnRequestBody {
    /**
    * Seller\'s comment on the rejection decision. This is where a seller will provide more information about rejecting the request. 
    */
    'comment'?: string;
    /**
    * Seller\'s decision for the request, available values: - `REJECT_REFUND`: seller reject a refund-only request - `REJECT_RETURN`: seller reject the initial return-and-refund request - `REJECT_RECEIVED_PACKAGE`: seller reject return-and-refund request after the buyer has already shipped or handed over the item. - `REJECT_REPLACEMENT`: seller reject replacement request
    */
    'decision'?: string;
    /**
    * List of images provided by the seller to support their decision to reject the return request. 
    */
    'images'?: Array<ReturnRefund202309RejectReturnRequestBodyImages>;
    /**
    * Seller\'s reason for rejecting the aftersales request. Use the [Get Decision Eligibility](https://partner.tiktokshop.com/docv2/page/69844a11eeba77049695c7f6) endpoint to retrieve the currently available rejection options for the same request, and submit the returned rejection reason name in this field. **Note**: The available decisions and rejection reasons can change depending on the current request status, so fetch eligibility again before calling this API.
    */
    'rejectReason'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "decision",
            "baseName": "decision",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ReturnRefund202309RejectReturnRequestBodyImages>"
        },
        {
            "name": "rejectReason",
            "baseName": "reject_reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309RejectReturnRequestBody.attributeTypeMap;
    }
}

