/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia';

export class ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason {
    'media'?: ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia;
    /**
    * Seller\'s reason for rejecting the aftersales request. Use the [Get Decision Eligibility](https://partner.tiktokshop.com/docv2/page/69844a11eeba77049695c7f6) endpoint to retrieve the currently available rejection options for the same request, and submit the returned rejection reason name in this field. **Note**: The available decisions and rejection reasons can change depending on the current request status, so fetch eligibility again before calling this API.
    */
    'reasonId'?: string;
    /**
    * Additional explanation for the decision.
    */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "media",
            "baseName": "media",
            "type": "ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia"
        },
        {
            "name": "reasonId",
            "baseName": "reason_id",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason.attributeTypeMap;
    }
}

