/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisions } from './ReviewAftersalesRequestBodyAftersalesRequestDecisions';

export class ReturnRefund202603ReviewAftersalesRequestBody {
    /**
    * Decisions to apply to aftersales requests.
    */
    'aftersalesRequestDecisions'?: Array<ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequestDecisions",
            "baseName": "aftersales_request_decisions",
            "type": "Array<ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisions>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBody.attributeTypeMap;
    }
}

