/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603ReviewAftersalesResponseDataErrors } from './ReviewAftersalesResponseDataErrors';

export class ReturnRefund202603ReviewAftersalesResponseData {
    /**
    * Lists errors for partially failed requests. For example, if a request reviews multiple orders or items and only some fail, individual error details are returned here.  **IMPORTANT**: Partial failures still return a top-level success code (0), so clients must also check this field to detect partial errors. For complete failures (e.g. validation errors), the top-level response code and message will indicate a failure, but this field will remain empty.
    */
    'errors'?: Array<ReturnRefund202603ReviewAftersalesResponseDataErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ReturnRefund202603ReviewAftersalesResponseDataErrors>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesResponseData.attributeTypeMap;
    }
}

