/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails {
    /**
    * Currency of the refund amount (ISO 4217). Must match the currency of the forward order.
    */
    'currency'?: string;
    /**
    * Proposed refund amount.
    */
    'partialRefundAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "partialRefundAmount",
            "baseName": "partial_refund_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsAlternativeSolutionDetails.attributeTypeMap;
    }
}

