/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems {
    /**
    * Unique identifier for this item in the return. In the case of virtual bundle, this corresponds to the id of the original parent item bundle.
    */
    'returnLineItemId'?: string;
    /**
    * Unique identifier for this item in the return. In the case of virtual bundle, this corresponds to the id of the current child item being returned.
    */
    'subReturnLineItemId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "returnLineItemId",
            "baseName": "return_line_item_id",
            "type": "string"
        },
        {
            "name": "subReturnLineItemId",
            "baseName": "sub_return_line_item_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsLineItems.attributeTypeMap;
    }
}

