/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions';

export class ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisions {
    /**
    * The timestamp at which the decision/action was made (in unix seconds).
    */
    'actionUnixTime'?: number;
    /**
    * The idempotency key is a unique value generated by the client which the server uses to recognize the same request. How you create unique keys is up to you, but we suggest using UUIDs, or another random string with enough entropy to avoid collisions. Idempotency keys can be up to 255 characters long.
    */
    'idempotencyKey'?: string;
    /**
    * Decisions applied at the line item level.
    */
    'lineItemDecisions'?: Array<ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions>;
    /**
    * Identifies the object upon which this decision is made.
    */
    'requestId'?: string;
    /**
    * Type of identifier provided in request_id. Possible values: - `AFTERSALES` - `RMA`
    */
    'requestIdType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actionUnixTime",
            "baseName": "action_unix_time",
            "type": "number"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string"
        },
        {
            "name": "lineItemDecisions",
            "baseName": "line_item_decisions",
            "type": "Array<ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisions>"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "requestIdType",
            "baseName": "request_id_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisions.attributeTypeMap;
    }
}

