/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesPriceDetail } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesPriceDetail';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesProductImage } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesProductImage';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLines {
    /**
    * Ignore this field. It is not yet supported.
    */
    'orderLineId'?: string;
    'priceDetail'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesPriceDetail;
    'productImage'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesProductImage;
    /**
    * Ignore this field. It is not yet supported.
    */
    'productName'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'sellerSkuName'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'skuId'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'skuName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderLineId",
            "baseName": "order_line_id",
            "type": "string"
        },
        {
            "name": "priceDetail",
            "baseName": "price_detail",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesPriceDetail"
        },
        {
            "name": "productImage",
            "baseName": "product_image",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLinesProductImage"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "sellerSkuName",
            "baseName": "seller_sku_name",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsExchangeOrderLines.attributeTypeMap;
    }
}

