/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFilters } from './SearchReturnMerchandiseAuthorizationRequestBodyFilters';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyPagination } from './SearchReturnMerchandiseAuthorizationRequestBodyPagination';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodySort } from './SearchReturnMerchandiseAuthorizationRequestBodySort';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBody {
    /**
    * Whitelist of field names to return additional data in the response. Possible values: Possible values: - LINE_ITEMS - SKU_RETURN_REQUESTS
    */
    'dataWhitelist'?: Array<string>;
    'filters'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFilters;
    'pagination'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyPagination;
    'sort'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodySort;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataWhitelist",
            "baseName": "data_whitelist",
            "type": "Array<string>"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFilters"
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyPagination"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodySort"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBody.attributeTypeMap;
    }
}

