/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime {
    /**
    * Exclusive upper bound (Unix seconds).
    */
    'maxUnixTimeExclusive'?: number;
    /**
    * Inclusive lower bound (Unix seconds).
    */
    'minUnixTimeInclusive'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxUnixTimeExclusive",
            "baseName": "max_unix_time_exclusive",
            "type": "number"
        },
        {
            "name": "minUnixTimeInclusive",
            "baseName": "min_unix_time_inclusive",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime.attributeTypeMap;
    }
}

