/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestRequestBodyFilters } from './SearchAftersalesRequestRequestBodyFilters';
import { ReturnRefund202603SearchAftersalesRequestRequestBodyPagination } from './SearchAftersalesRequestRequestBodyPagination';
import { ReturnRefund202603SearchAftersalesRequestRequestBodySort } from './SearchAftersalesRequestRequestBodySort';

export class ReturnRefund202603SearchAftersalesRequestRequestBody {
    'filters'?: ReturnRefund202603SearchAftersalesRequestRequestBodyFilters;
    'pagination'?: ReturnRefund202603SearchAftersalesRequestRequestBodyPagination;
    'sort'?: ReturnRefund202603SearchAftersalesRequestRequestBodySort;
    /**
    * Whitelist of field names to return additional data in the response. Possible values: - `LINE_ITEMS` - `SKU_RETURN_REQUESTS` - `RETURN_MERCHANDISE_AUTHORIZATIONS`
    */
    'whitelistedDataFields'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodyFilters"
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodyPagination"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodySort"
        },
        {
            "name": "whitelistedDataFields",
            "baseName": "whitelisted_data_fields",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestRequestBody.attributeTypeMap;
    }
}

