/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizationsLineItems } from './SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizationsLineItems';

export class ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations {
    /**
    * Identifier of the parent aftersales request.
    */
    'aftersalesRequestId'?: string;
    /**
    * Unique identifier for this RMA data.
    */
    'id'?: string;
    /**
    * List of items associated with this aftersales request.
    */
    'lineItems'?: Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizationsLineItems>;
    /**
    * Identifier of the associated physical return package.
    */
    'packageId'?: string;
    /**
    * The current state of this RMA data. Possible values: - `INIT` - `AWAITING_BUYER_RETURN` - `RETURN_IN_TRANSIT` - `PENDING_PACKAGE_REVIEW` - `PACKAGE_REVIEW_COMPLETED`
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequestId",
            "baseName": "aftersales_request_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizationsLineItems>"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations.attributeTypeMap;
    }
}

