/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsProductImage } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsProductImage';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsRefundAmount } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsRefundAmount';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItems {
    /**
    * Order line ID.
    */
    'orderLineItemId'?: string;
    'productImage'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsProductImage;
    /**
    * Product name.
    */
    'productName'?: string;
    'refundAmount'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsRefundAmount;
    /**
    * Return order line ID.
    */
    'returnLineItemId'?: string;
    /**
    * Return sub order line ID.
    */
    'returnSubLineItemId'?: string;
    /**
    * SKU name defined by seller.
    */
    'sellerSku'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;
    /**
    * SKU name.
    */
    'skuName'?: string;
    /**
    * Sub order line ID.
    */
    'subOrderLineItemId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderLineItemId",
            "baseName": "order_line_item_id",
            "type": "string"
        },
        {
            "name": "productImage",
            "baseName": "product_image",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsProductImage"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "refundAmount",
            "baseName": "refund_amount",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItemsRefundAmount"
        },
        {
            "name": "returnLineItemId",
            "baseName": "return_line_item_id",
            "type": "string"
        },
        {
            "name": "returnSubLineItemId",
            "baseName": "return_sub_line_item_id",
            "type": "string"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        },
        {
            "name": "subOrderLineItemId",
            "baseName": "sub_order_line_item_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequestsReturnSubLineItems.attributeTypeMap;
    }
}

