/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeCreateTime } from './SearchAftersalesRequestRequestBodyFiltersTimeCreateTime';
import { ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeUpdateTime } from './SearchAftersalesRequestRequestBodyFiltersTimeUpdateTime';

export class ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTime {
    'createTime'?: ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeCreateTime;
    'updateTime'?: ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeUpdateTime;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeCreateTime"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTimeUpdateTime"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTime.attributeTypeMap;
    }
}

