/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequests } from './SearchAftersalesRequestResponseDataAftersalesRequests';

export class ReturnRefund202603SearchAftersalesRequestResponseData {
    /**
    * List of aftersales (return) request data.
    */
    'aftersalesRequests'?: Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequests>;
    /**
    * Used to fetch the next page/set of results.
    */
    'nextPageToken'?: string;
    /**
    * The total result set size, independent of pagination.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequests",
            "baseName": "aftersales_requests",
            "type": "Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequests>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestResponseData.attributeTypeMap;
    }
}

