/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeCreateTime } from './SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeCreateTime';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime } from './SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime {
    'createTime'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeCreateTime;
    'updateTime'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeCreateTime"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTimeUpdateTime"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime.attributeTypeMap;
    }
}

