/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTime } from './SearchAftersalesRequestRequestBodyFiltersTime';

export class ReturnRefund202603SearchAftersalesRequestRequestBodyFilters {
    /**
    * Restricts results to the specified aftersales requests.
    */
    'aftersalesRequestIds'?: Array<string>;
    /**
    * Restricts results to the specified aftersales request statuses. Possible values: - `INIT` - `PENDING_REQUEST_REVIEW` - `REQUEST_REVIEW_COMPLETED`
    */
    'aftersalesRequestStatuses'?: Array<string>;
    /**
    * Restricts results to aftersales request data which includes at least one sku return request with a given buyer id.
    */
    'buyerIds'?: Array<string>;
    /**
    * Restricts results to aftersales request data which includes at least one sku return request with a given main (forward) order id.
    */
    'mainOrderIds'?: Array<string>;
    /**
    * Restricts results to aftersales request data which includes at least one sku return request with a given type. Possible values: - `REFUND` - `RETURN_AND_REFUND` - `REPLACEMENT`
    */
    'returnTypes'?: Array<string>;
    'time'?: ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTime;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequestIds",
            "baseName": "aftersales_request_ids",
            "type": "Array<string>"
        },
        {
            "name": "aftersalesRequestStatuses",
            "baseName": "aftersales_request_statuses",
            "type": "Array<string>"
        },
        {
            "name": "buyerIds",
            "baseName": "buyer_ids",
            "type": "Array<string>"
        },
        {
            "name": "mainOrderIds",
            "baseName": "main_order_ids",
            "type": "Array<string>"
        },
        {
            "name": "returnTypes",
            "baseName": "return_types",
            "type": "Array<string>"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "ReturnRefund202603SearchAftersalesRequestRequestBodyFiltersTime"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestRequestBodyFilters.attributeTypeMap;
    }
}

