/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603SearchAftersalesRequestRequestBodyPagination {
    /**
    * Number of records to return per page, max 100.
    */
    'pageSize'?: number;
    /**
    * Identifies the page to retrieve.
    */
    'pageToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number"
        },
        {
            "name": "pageToken",
            "baseName": "page_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestRequestBodyPagination.attributeTypeMap;
    }
}

