/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime } from './SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFilters {
    /**
    * Restricts results to the specified aftersales requests.
    */
    'aftersalesRequestIds'?: Array<string>;
    /**
    * Restricts results to the specified main (forward) order IDs.
    */
    'mainOrderIds'?: Array<string>;
    /**
    * Restricts results to the specified packages.
    */
    'packageIds'?: Array<string>;
    /**
    * Restricts results to the specified RMA data.
    */
    'rmaIds'?: Array<string>;
    /**
    * Restricts results to the specified RMA data statuses. Possible values: - INIT - AWAITING_BUYER_RETURN - RETURN_IN_TRANSIT - PENDING_PACKAGE_REVIEW - PACKAGE_REVIEW_COMPLETED
    */
    'statuses'?: Array<string>;
    'time'?: ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequestIds",
            "baseName": "aftersales_request_ids",
            "type": "Array<string>"
        },
        {
            "name": "mainOrderIds",
            "baseName": "main_order_ids",
            "type": "Array<string>"
        },
        {
            "name": "packageIds",
            "baseName": "package_ids",
            "type": "Array<string>"
        },
        {
            "name": "rmaIds",
            "baseName": "rma_ids",
            "type": "Array<string>"
        },
        {
            "name": "statuses",
            "baseName": "statuses",
            "type": "Array<string>"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFiltersTime"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationRequestBodyFilters.attributeTypeMap;
    }
}

