/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsLineItems } from './SearchAftersalesRequestResponseDataAftersalesRequestsLineItems';
import { ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations } from './SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations';
import { ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequests } from './SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequests';

export class ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequests {
    /**
    * Unique identifier for this aftersales request.
    */
    'id'?: string;
    /**
    * List of items associated with this aftersales request.
    */
    'lineItems'?: Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsLineItems>;
    /**
    * Associated RMA (return package) records.
    */
    'returnMerchandiseAuthorizations'?: Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations>;
    /**
    * SKU-level, sub return requests associated with this aftersales request (also known as \"reverse orders\" or \"return requests\").
    */
    'skuReturnRequests'?: Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequests>;
    /**
    * Current state of this aftersales request. Possible values: - `INIT` - `PENDING_REQUEST_REVIEW` - `REQUEST_REVIEW_COMPLETED`
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsLineItems>"
        },
        {
            "name": "returnMerchandiseAuthorizations",
            "baseName": "return_merchandise_authorizations",
            "type": "Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsReturnMerchandiseAuthorizations>"
        },
        {
            "name": "skuReturnRequests",
            "baseName": "sku_return_requests",
            "type": "Array<ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequests>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequests.attributeTypeMap;
    }
}

