/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603SearchAftersalesRequestRequestBodySort {
    /**
    * Name of the field used for sorting. Possible values: - `CREATE_TIME` - `UPDATE_TIME` 
    */
    'sortField'?: string;
    /**
    * Sort direction. Possible values: - `ASC` - `DESC`
    */
    'sortOrder'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sortField",
            "baseName": "sort_field",
            "type": "string"
        },
        {
            "name": "sortOrder",
            "baseName": "sort_order",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestRequestBodySort.attributeTypeMap;
    }
}

