/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsLineItems } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsLineItems';
import { ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequests } from './SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequests';

export class ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations {
    /**
    * Identifier of the parent aftersales request.
    */
    'aftersalesRequestId'?: string;
    /**
    * Unique identifier for this RMA data.
    */
    'id'?: string;
    /**
    * Item units expected in the return package.
    */
    'lineItems'?: Array<ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsLineItems>;
    /**
    * Identifier of the associated physical return package.
    */
    'packageId'?: string;
    /**
    * Associated SKU-level, sub return requests.
    */
    'skuReturnRequests'?: Array<ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequests>;
    /**
    * The current state of this RMA data. Possible values: - INIT - AWAITING_BUYER_RETURN - RETURN_IN_TRANSIT - PENDING_PACKAGE_REVIEW - PACKAGE_REVIEW_COMPLETED
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aftersalesRequestId",
            "baseName": "aftersales_request_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsLineItems>"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "skuReturnRequests",
            "baseName": "sku_return_requests",
            "type": "Array<ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizationsSkuReturnRequests>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchReturnMerchandiseAuthorizationResponseDataReturnMerchandiseAuthorizations.attributeTypeMap;
    }
}

