/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequestsExchangeOrderLinesPriceDetail {
    /**
    * Ignore this field. It is not yet supported.
    */
    'currency'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'refundShippingFee'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'refundSubtotal'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'refundTax'?: string;
    /**
    * Ignore this field. It is not yet supported.
    */
    'refundTotal'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "refundShippingFee",
            "baseName": "refund_shipping_fee",
            "type": "string"
        },
        {
            "name": "refundSubtotal",
            "baseName": "refund_subtotal",
            "type": "string"
        },
        {
            "name": "refundTax",
            "baseName": "refund_tax",
            "type": "string"
        },
        {
            "name": "refundTotal",
            "baseName": "refund_total",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsSkuReturnRequestsExchangeOrderLinesPriceDetail.attributeTypeMap;
    }
}

