/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsLineItems {
    /**
    * Identifier of the associated main (forward) order.
    */
    'mainOrderId'?: string;
    /**
    * Unique identifier for this item in the return. In the case of virtual bundle, this is corresponds to the id of the original parent item bundle.
    */
    'returnLineItemId'?: string;
    /**
    * SKU identifier associated with this item (for product details).
    */
    'skuId'?: string;
    /**
    * Identifier of the associated SKU-level, sub return request.
    */
    'skuReturnRequestId'?: string;
    /**
    * Unique identifier for this item in the return. In the case of virtual bundle, this is corresponds to the id of the current child item being returned.
    */
    'subReturnLineItemId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mainOrderId",
            "baseName": "main_order_id",
            "type": "string"
        },
        {
            "name": "returnLineItemId",
            "baseName": "return_line_item_id",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuReturnRequestId",
            "baseName": "sku_return_request_id",
            "type": "string"
        },
        {
            "name": "subReturnLineItemId",
            "baseName": "sub_return_line_item_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603SearchAftersalesRequestResponseDataAftersalesRequestsLineItems.attributeTypeMap;
    }
}

