/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Fulfillment202601RedeemInfoCallbackRequestBodyOrderInfoListRedeemInfo {
    /**
    * Set the redeem data to this field with the maximum number of characters 1200. The example of each type is shown below, CODE: abc12344 URL: https://{your_domain}/abc CODE_PIN(json format):  {\"type\": \"CODE_PIN\",\"code\": \"12345\",\"pin\": \"abc\"}
    */
    'redeemData'?: string;
    /**
    * Additional redemption instruction in JSON format. Use instruction_url to specify a third-party website where the buyer completes redemption. This URL is included as a clickable link in the fulfillment email. Example: {\"instruction_url\": \"https://example.com/redeem\"}
    */
    'redeemInstructionInfo'?: string;
    /**
    * What redeem type that you callback. \'CODE\' - type code \'URL\' - type url \'CODE_PIN\' - type pin and code
    */
    'redeemType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "redeemData",
            "baseName": "redeem_data",
            "type": "string"
        },
        {
            "name": "redeemInstructionInfo",
            "baseName": "redeem_instruction_info",
            "type": "string"
        },
        {
            "name": "redeemType",
            "baseName": "redeem_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202601RedeemInfoCallbackRequestBodyOrderInfoListRedeemInfo.attributeTypeMap;
    }
}

