/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202601GetDecisionEligibilityResponseDataDecisionsAvailableRejectReasons {
    /**
    * The reject reason name seller can use to reject buyer\'s return or cancellation request.
    */
    'name'?: string;
    /**
    * The display text for the reject reason.
    */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202601GetDecisionEligibilityResponseDataDecisionsAvailableRejectReasons.attributeTypeMap;
    }
}

