/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202602CreateReturnRequestBodyOrderLineList } from './CreateReturnRequestBodyOrderLineList';
import { ReturnRefund202602CreateReturnRequestBodySkus } from './CreateReturnRequestBodySkus';

export class ReturnRefund202602CreateReturnRequestBody {
    /**
    * Currency for refund which should be same as currency in TikTok Ship Order.
    */
    'currency'?: string;
    /**
    * **Optional**. Only applicable when shipment_type is `PLATFORM`. Specifies the handover method the buyer uses to return the item through platform-supported shipping. Supported values: - `DROP_OFF` - `PICKUP`
    */
    'handoverMethod'?: string;
    /**
    * Tiktok Shop order id
    */
    'orderId'?: string;
    /**
    * Specifies the order line IDs to include in the return request. If the order has been split into multiple packages, use order line IDs to create the return request. If neither order_line_item_ids nor skus is provided, the default is all order lines in the order. **Note:** This is a legacy field for new integrations use `order_line_list` instead.
    */
    'orderLineItemIds'?: Array<string>;
    /**
    * Specifies the line items to include in the return request and supports bundle order splitting. In one request, use either `order_line_item_id` for normal order lines or `sub_order_line_item_id` for bundle sub-items. **Note:** This field is completely backward compatible with the previous `order_line_items_ids` field.
    */
    'orderLineList'?: Array<ReturnRefund202602CreateReturnRequestBodyOrderLineList>;
    /**
    * Total refund amount to the buyer.  The total refund amount can not exceed the refundable amount
    */
    'refundTotal'?: string;
    /**
    * Seller\'s reason to create a return
    */
    'returnReason'?: string;
    /**
    * Which type to create:  - REFUND - RETURN_AND_REFUND
    */
    'returnType'?: string;
    /**
    * Specifies the return shipping method the buyer uses to send items back to the seller in a return request. Supported values: - `PLATFORM` - `BUYER_ARRANGE`
    */
    'shipmentType'?: string;
    /**
    * Skus
    */
    'skus'?: Array<ReturnRefund202602CreateReturnRequestBodySkus>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "handoverMethod",
            "baseName": "handover_method",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "orderLineItemIds",
            "baseName": "order_line_item_ids",
            "type": "Array<string>"
        },
        {
            "name": "orderLineList",
            "baseName": "order_line_list",
            "type": "Array<ReturnRefund202602CreateReturnRequestBodyOrderLineList>"
        },
        {
            "name": "refundTotal",
            "baseName": "refund_total",
            "type": "string"
        },
        {
            "name": "returnReason",
            "baseName": "return_reason",
            "type": "string"
        },
        {
            "name": "returnType",
            "baseName": "return_type",
            "type": "string"
        },
        {
            "name": "shipmentType",
            "baseName": "shipment_type",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<ReturnRefund202602CreateReturnRequestBodySkus>"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202602CreateReturnRequestBody.attributeTypeMap;
    }
}

