/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202602GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList } from './GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList';

export class ReturnRefund202602GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility {
    /**
    * A list of reason names that can be used when creating a follow-up aftersale request.
    */
    'availableReasonNames'?: Array<string>;
    /**
    * Use this field to recognize whether an item is eligible for an aftersale request: - `TRUE` - `FALSE`
    */
    'eligible'?: boolean;
    /**
    * The reason code for an ineligible aftersale request.
    */
    'ineligibleCode'?: number;
    /**
    * The reason for an ineligible aftersale request.
    */
    'ineligibleReason'?: string;
    /**
    * Specifies the order line IDs. **Note:** This is a legacy field for new integrations use `order_line_list` instead.
    */
    'orderLineItemsIds'?: Array<string>;
    /**
    * Specifies the order line items. **Note:** This field is completely backward compatible with the previous `order_line_items_ids` field.
    */
    'orderLineList'?: Array<ReturnRefund202602GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList>;
    /**
    * Aftersale request type. Possible values: - `CANCEL` - `RETURN` - `RETURN_AND_REFUND`
    */
    'requestType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "availableReasonNames",
            "baseName": "available_reason_names",
            "type": "Array<string>"
        },
        {
            "name": "eligible",
            "baseName": "eligible",
            "type": "boolean"
        },
        {
            "name": "ineligibleCode",
            "baseName": "ineligible_code",
            "type": "number"
        },
        {
            "name": "ineligibleReason",
            "baseName": "ineligible_reason",
            "type": "string"
        },
        {
            "name": "orderLineItemsIds",
            "baseName": "order_line_items_ids",
            "type": "Array<string>"
        },
        {
            "name": "orderLineList",
            "baseName": "order_line_list",
            "type": "Array<ReturnRefund202602GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList>"
        },
        {
            "name": "requestType",
            "baseName": "request_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202602GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility.attributeTypeMap;
    }
}

