/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202602SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
    /**
    * **Optional.** For buyer-initiated cancellation requests that still require seller handling, the action value is `SELLER_RESPOND_CANCEL`
    */
    'action'?: string;
    /**
    * Unix timestamp indicating the deadline for when the seller must perform the next action.
    */
    'deadline'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202602SearchCancellationsResponseDataCancellationsSellerNextActionResponse.attributeTypeMap;
    }
}

